### ISSUE TITLE
No input possible after screensaver deactivates for ~2 sec.

### ISSUE THREAD

**Issue by tadly** [j-a-n/lovelace-wallpanel#100]
When I tap the screen so wallpanel deactivates and shows me my dashboard, I'm unable to perform any action for about 2 seconds.
I am not sure if this is a problem with my config or a general issue with wallpanel.

I can confirm this issue on my amazon fire tablet (with touch input) and my xps13 using the touchpad with an up-to-date browser (edge in my case).

For reference, this is my config (I didn't omit anything just in case):
```yaml
wallpanel:
  enabled: false
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: false
  idle_time: 7
  image_url: ''
  info_move_pattern: random
  info_move_interval: 60
  info_move_fade_duration: 1
  style:
    wallpanel-screensaver-overlay:
      background: '#00000080'
  cards:
    - type: markdown
      content: >
        {% set time = now() %} <center><font
        size="7"><b>{{time.strftime(('%H:%M'))}}</b></font></center>
        <center><font size="5">{{ time.strftime('%a, %d %B
        %Y')}}</font></center>
      wp_style:
        '--ha-card-background': none
        '--ha-card-box-shadow': none
        '--ha-card-border-width': 0px
        '--primary-text-color': '#e1e1e1'
        '--secondary-text-color': '#9b9b9b'
    - type: horizontal-stack
      wp_style:
        '--ha-card-background': none
        '--ha-card-box-shadow': none
        '--ha-card-border-width': 0px
        '--primary-text-color': '#e1e1e1'
        '--secondary-text-color': '#9b9b9b'
      cards:
        - type: custom:mushroom-entity-card
          entity: weather.home
          primary_info: state
          secondary_info: none
          icon_color: disabled
        - type: custom:mushroom-template-card
          primary: >-
            {{ state_attr('weather.home', 'temperature')}} {{
            state_attr('weather.home', 'temperature_unit')}}
          secondary: ''
          icon: mdi:heat-wave
          entity: weather.home
          icon_color: >-
            {% set temp = state_attr('weather.home', 'temperature') %} {{ 'blue'
            if temp < 10 }} {{ 'orange' if 10 <= temp <= 20 }} {{ 'red' if temp
            >= 20 }}
        - type: custom:mushroom-template-card
          primary: >-
            {{ state_attr('weather.home', 'wind_speed')}} {{
            state_attr('weather.home', 'wind_speed_unit')}}
          secondary: ''
          icon: mdi:weather-windy
          entity: weather.home
          icon_color: >-
            {% set wspeed = state_attr('weather.home', 'wind_speed') %} {{
            'green' if 5 <= wspeed <= 10 }} {{ 'purple' if 10 <= wspeed <= 20 }}
            {{ 'red' if wspeed >= 20 }}
    - type: custom:mushroom-chips-card
      wp_style:
        '--ha-card-background': none
        '--ha-card-box-shadow': none
        '--ha-card-border-width': 0px
        '--primary-text-color': '#e1e1e1'
        '--secondary-text-color': '#9b9b9b'
      chips:
        - type: conditional
          conditions:
            - entity: group.living_room
              state: 'on'
          chip:
            type: entity
            entity: group.living_room
            icon: mdi:sofa
            content_info: name
        - type: conditional
          conditions:
            - entity: group.kitchen
              state: 'on'
          chip:
            type: entity
            entity: group.kitchen
            icon: mdi:sofa
            content_info: name
        - type: conditional
          conditions:
            - entity: group.office
              state: 'on'
          chip:
            type: entity
            entity: group.office
            icon: mdi:sofa
            content_info: name
        - type: conditional
          conditions:
            - entity: group.bathroom
              state: 'on'
          chip:
            type: entity
            entity: group.bathroom
            icon: mdi:sofa
            content_info: name
        - type: conditional
          conditions:
            - entity: group.bedroom
              state: 'on'
          chip:
            type: entity
            entity: group.bedroom
            icon: mdi:sofa
            content_info: name
views:
...
```
