### ISSUE TITLE
Feature Request - disable background image

### ISSUE THREAD

**Issue by RWSF74** [j-a-n/lovelace-wallpanel#108]
Is it possible to disable the background images?

**Comment by j-a-n** [comment]
Yes, you can set an empty image_url:
```yaml
wallpanel:
  image_url:
```

**Comment by RWSF74** [comment]
Thanks for your quick reply.
OK, but when I do that, the background becomes transparent and the current dashboard is slightly visible through the wallpanel. I'd like to have a (clean) black background, but I can't find any (non)transparency-settings.. I hope you can help me, thanks in advance!

**Comment by j-a-n** [comment]
This should not be the default.
How does your wallpanel config look like?
You can change the background color using styles:
```yaml
wallpanel:
  style:
    wallpanel-screensaver-container:
      background-color: '#000000'
```
