### ISSUE TITLE
Alter top and left margin?

### ISSUE THREAD

**Issue by RWSF74** [j-a-n/lovelace-wallpanel#111]
Is it possible to alter the top and left margin of the container?
![Schermafbeelding 2023-05-11 165707](https://github.com/j-a-n/lovelace-wallpanel/assets/118888061/8dc50072-55eb-42fe-abe7-6b421f8b395c)
I'm using your Wall-Panel on an NSPanel Pro, where every pixel counts :)
Thanks for your reply (and Wall-Panel ofcourse!)

**Comment by j-a-n** [comment]
You can set the container padding:
```yaml
wallpanel:
  style:
    wallpanel-screensaver-info-container:
      padding: 5px
```
