### ISSUE TITLE
Stop screensaver by using browser_mod doesn't work starting with HA 2023.5

### ISSUE THREAD

**Issue by amaciuc** [j-a-n/lovelace-wallpanel#121]
This [chapter](https://github.com/j-a-n/lovelace-wallpanel#integration-with-browser_mod) shows an example how to wake from screensaver using `browser_mod`:
> document.getElementsByTagName("wallpanel-view")[0].stopScreensaver();

From some reason, starting with HA `2023.5`, this command doesn't work anymore (It does nothing). I am not sure where the problem comes from, `browser_mod` (version `2.2.2`) or `lovelace-wallpaper` (version `4.11.1`). 

The command is:
```yaml
service: browser_mod.javascript
data:
  code: document.getElementsByTagName("wallpanel-view")[0].stopScreensaver();
  browser_id: <YOUR_BROWSER_ID>
```

Can someone check this command and give me a feedback if it will work for you ?
