### ISSUE TITLE
Feature Request - Ken Burns effect on picture

### ISSUE THREAD

**Issue by amondit** [j-a-n/lovelace-wallpanel#122]
Hello, (and thanks for the good work!)

I'm using this along with the Google Photos integration, works great! However some pictures have an aspect ratio that makes them cut when displayed, and also appear a bit 'static' without animation.

Would it be possible to add some moving effects on the pictures (like the ken burns effect, for example), maybe done through css transformations?

Many thanks!

**Comment by j-a-n** [comment]
Thank you, this is a very nice idea!
I have started to implement the effect in v4.14.0.
You can activate it with:
```yaml
config:
  image_animation_ken_burns: true
  image_animation_ken_burns_zoom: 1.3
```
Feedback is welcome!
