### ISSUE TITLE
Entity not available: weather.home

### ISSUE THREAD

**Issue by Panzerkrokette** [j-a-n/lovelace-wallpanel#130]
I did get wallpanel to run with google photos just fine but after a while the weather card vanished and only shows entity not available: weather.home. https://imgur.com/a/NDpoVtL

The entity is available and my weather cards and automations are working just fine. I reinstalled wallpanel and the openweathermap integration but it didn't help.

Any ideas how to solve this? Really loving wallpanel so far, great work!

Here's my code so far:

```
wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: false
  idle_time: 5
  display_time: 10
  image_url: media-entity://camera.google_photos_favorites_media
  image_fit: cover
  crop_mode: original
  style: null
style:
  wallpanel-screensaver-container:
    background-color: '#333333dd'
  wallpanel-screensaver-info-box:
    '--wp-card-width': 900px
    background-color: '#ffffff99'
    box-shadow: >-
      0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0, 0.14),
      0px 1px 3px 0px rgba(0, 0, 0, 0.12)
  wallpanel-screensaver-info-box-content:
    '--ha-card-background': none
    '--ha-card-box-shadow': none
    '--primary-background-color': '#fafafa'
    '--secondary-background-color': '#e5e5e5'
    '--primary-text-color': '#212121'
    '--secondary-text-color': '#727272'
  cards:
    - type: vertical-stack
      cards:
        - type: custom:weather-card
          details: true
          forecast: true
          hourly_forecast: false
          name: Wetter
          entity: weather.home
          current: true
          number_of_forecasts: '6'
views:
  - title: Home
```

**Comment by j-a-n** [comment]
Are you sure that `weather.home` ist the correct entity?
Please check in Settings => Entities if there are other openweathermap entities.

**Comment by Dujing-yang** [comment]
I use the computer browser to load the card, but I have tried many times without success to implement the screen in the example, and I can't even enter the protection. I hope you can give me an example and attach a picture below so that I can have a more intuitive example. Here's the example I used, where I left both my mouse and keyboard motionless for a long time, but failed to enter the wall panel                                                                    
wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  idle_time:  1
views:
  - title: Home

**Comment by harryfine** [comment]
A $25 Canadian coffee for help please.
Can't show weather on card.  Just get error that the entity weather.home. is not available.  weather.home is not a valid entity on my installation of homeassistant, but as you can see from the automation, I've used a proper entity that works perfectly as a card on my regular dashboard.

I've added the Openweathermap integration and have the API, and the same card is working on my homeassistant dashboard showing weather.

wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: true
  idle_time: 30
  keep_screen_on_time: 0
  fade_in_time: 2
  crossfade_time: 2
  display_time: 20
  image_fit: cover
  crop_mode: original
  control_reactivation_time: 0.5
style:
  wallpanel-screensaver-container:
    background-color: '#333333dd'
  wallpanel-screensaver-info-box:
    '--wp-card-width': 900px
    background-color: '#ffffff99'
    box-shadow: >-
      0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0, 0.14),
      0px 1px 3px 0px rgba(0, 0, 0, 0.12)
  wallpanel-screensaver-info-box-content:
    '--ha-card-background': none
    '--ha-card-box-shadow': none
    '--primary-background-color': '#fafafa'
    '--secondary-background-color': '#e5e5e5'
    '--primary-text-color': '#212121'
    '--secondary-text-color': '#727272'
  image_url: https://source.unsplash.com/random/${1920}x${1080}?dogs
  cards:
    - type: vertical-stack
      cards:
        - type: custom:weather-card
          details: true
          forecast: true
          hourly_forecast: false
          name: Wetter
          entity: weather.openweathermap
          current: true
          number_of_forecasts: '6'
title: Front Door Kiosk
.
.
Will pay by PayPal or Buy Me a Coffee or whatever for this solutoin.

**Comment by Panzerkrokette** [comment]
It's the same for me like for Harryfine. I even edited the json to match my
entities but it still only shows weather.home not available even if I
change it to weather.openweathermap.

The misterious thing is I can't grasp when wallpanel stopped working and
starting showing this message.

It used to work just fine and I played around a bit with my cards and the
next day all cards were gone and only entity unavailable: weather.home
prevails.

harryfine ***@***.***> schrieb am So., 30. Juli 2023, 17:37:

**Comment by harryfine** [comment]
Maybe you can add $25 and get this thing fixed???

**Comment by harryfine** [comment]
I have tried so many different entities, openweathermap entities, but always the same error message.  Yet the same entities show up on my dashboards in weather cards or entity cards.  

It seems the code is looking for weather.home, perhaps that's the default, but it's not picking up my entities.

**Comment by Panzerkrokette** [comment]
It actually is looking for weather.home by default, that's why I edited it
and changed the entity to weather.openweathermap, but still no luck.

Fun fact is that it used to work just fine with weather.home and nothing
ever edited but it just suddenly stopped working at all.

harryfine ***@***.***> schrieb am Mo., 31. Juli 2023, 21:20:

**Comment by harryfine** [comment]
How did it work just fine with weather.home unless you had an entity of that name?

**Comment by Panzerkrokette** [comment]
I had, It's the default name given to the weather entity, but the ID is
weather.openweathermap.

harryfine ***@***.***> schrieb am Mo., 31. Juli 2023, 21:35:

**Comment by Panzerkrokette** [comment]
I finally solved it by also changing the entity ID of my weather.home
entity to weather.home, not only the entity name.

Am Mo., 31. Juli 2023 um 21:49 Uhr schrieb Stefan Magener <
***@***.***>:

**Comment by Oldertarl** [comment]
I do not see how this could be closed?
The same issue still happens when a fresh install of wallpanel is done.
The right entity name should be "weather.forecast_home"
kindly address this where I can change this, or remove ( if no weather should be displayed )

**Comment by j-a-n** [comment]
Please have a look at the [documentation](https://j-a-n.github.io/lovelace-wallpanel/info-box/#cards)

**Comment by Oldertarl** [comment]
I have gone over the documentation, still the entity remains not present
Please see below the start of the yaml raw edit 
Hope this helps understanding my issue better 

`wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: false
  idle_time: 5
  cards:
    - type: weather-forecast
      entity: weather.home
      show_forecast: true
      forecast_type: daily`

**Comment by j-a-n** [comment]
Shouldn't it be:
```yaml
wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: false
  idle_time: 5
  cards:
    - type: weather-forecast
      entity: weather.forecast_home
      show_forecast: true
      forecast_type: daily
```
