### ISSUE TITLE
Ruins touch controls upon hiding both bars

### ISSUE THREAD

**Issue by IanEatsBabies** [j-a-n/lovelace-wallpanel#131]
Using the following YAML Wallpanel seems to destroy any and all forms of touch controls on three seperate phones and one tablet (only four I tested). On PC however everything responds fine.

It's just a single Panel view, filled with a slider-button-card (turning old phones into lightswitches). Everything works fine until both hide_toolbar and hide_sidebar are set to true.

Funny thing is, same thing happened with Kiosk mode.

```
wallpanel:
  enabled: true
  card_interaction: true
  hide_toolbar: true
  hide_sidebar: true
views:
  - title: Home
    type: panel
    badges: []
    cards:
      - type: custom:slider-button-card
        entity: light.bathroom
        slider:
          direction: left-right
          background: solid
          use_state_color: true
          use_percentage_bg_opacity: true
          show_track: false
          toggle_on_click: false
          force_square: false
        show_name: false
        show_state: false
        compact: false
        icon:
          show: false
          use_state_color: false
          tap_action:
            action: more-info
          icon: ''
        action_button:
          mode: toggle
          icon: mdi:power
          show: false
          show_spinner: true
          tap_action:
            action: toggle
```
