### ISSUE TITLE
card interaction does not work for 2nd card in a row

### ISSUE THREAD

**Issue by schreyack** [j-a-n/lovelace-wallpanel#133]
I have a grid of cards being shown in the info box and I used a horizontal stack for each row, because I couldn't get the wp_style grid-row and grid-column to work correctly (I can't seem to set the column-gap to 0).  But with the cards in a horizontal stack, only the first card in the row can be interacted with, the second card in the row does not respond.

In this picture, for example, I can tap on pool controls and interact with it, but i can not tap on spa controls and interact with that.
![IMG_1431](https://github.com/j-a-n/lovelace-wallpanel/assets/13837844/c63bd200-6285-4fbf-8044-6b33cd5c0159)

**Comment by j-a-n** [comment]
Could you please post (a part) of your config?

**Comment by schreyack** [comment]
this is the relevant parts ( i think)

```
# lovelace_gen
{% set width = "350px" %}
{% set height = "250px" %}
{% set redirect_height = "200px" %}
{% set name_font = "50px" %}
{% set state_font = "100px" %}
{% set label_font = "50px" %}

button_card_templates: !include_dir_named button-card-templates

wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: true
  idle_time: 60
  black_screen_after_time: 0
  display_time: 1
  image_url: /
  card_interaction: true
  cards:
    - type: horizontal-stack
      cards:
        - !include 
          - cards/pool/redirect.yaml
          - width: {{ width }}
            height: {{ redirect_height }}
            name_font: {{ name_font }}
            name: Pool Controls
            path: '/home-dashboard/pool_panel'
            color: blue
            icon: mdi:pool
    - type: horizontal-stack
      cards:
        - !include 
          - cards/pool/redirect.yaml
          - width: {{ width }}
            height: {{ redirect_height }}
            name_font: {{ name_font }}
            name: Spa Controls
            path: '/home-dashboard/spa_panel'
            color: green
            icon: mdi:spa
```

**Comment by j-a-n** [comment]
The following example displays 2x2 cards with 0 margin.
```yaml
wallpanel:
  style:
    wallpanel-screensaver-info-box:
      '--wp-card-margin': 0px
  cards:
    - type: markdown
      content: Card 1
      wp_style:
        width: 200px
        height: 200px
        grid-row: 1
        grid-column: 1
    - type: markdown
      content: Card 2
      wp_style:
        width: 200px
        height: 200px
        grid-row: 1
        grid-column: 2
    - type: markdown
      content: Card 3
      wp_style:
        width: 200px
        height: 200px
        grid-row: 2
        grid-column: 1
    - type: markdown
      content: Card 4
      wp_style:
        width: 200px
        height: 200px
        grid-row: 2
        grid-column: 2
```
