### ISSUE TITLE
Changing ha card background

### ISSUE THREAD

**Issue by tntn04** [j-a-n/lovelace-wallpanel#136]
Hello,

I am trying to change the ha card background and followed the example to change the weather card as shown.

```yaml
cards:
  - type: weather-forecast
    entity: weather.home
    wp_style:
      margin-top: 10px
      '--ha-card-background': '#990000'
```

My card using the example is this.

```yaml
wallpanel:
  enabled: false
  idle_time: 0
  hide_toolbar: true
  hide_toolbar_action_icons: true
  hide_sidebar: true
  debug: false
title: My Bedroom
views:
  - theme: Backend-selected
    path: default_view
    title: My Bedroom
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - show_name: true
            show_icon: true
            show_state: true
            type: glance
            entities:
              - entity: binary_sensor.aqara_door_and_window_sensor_p2_door
                name: CL Door
              - entity: light.hue_white_lamp_1
                name: CL Light
              - entity: sensor.ms1_lux
                name: Light
              - entity: sensor.ms1_temperature
                name: Temp
              - entity: sensor.ms1_humidity
                name: Hum
              - entity: sensor.qnapups_status
                name: UPS
            wp_style:
              '--ha-card-background': '#000000'
            columns: 4
            state_color: true
          - show_name: true
            show_icon: true
            show_state: true
            type: glance
            entities:
              - entity: light.kl135_1
                name: Desk 1
              - entity: light.kl135_2
                name: Desk 2
              - entity: light.bed_1
                name: Ceiling 1
              - entity: light.bed_2
                name: Ceiling 2
            columns: 4
```
I access the card via http://192.168.111.233:8123/dashboard-magicmirror/default_view?wp_enabled=true to enable wallpanel but the background color is still the default ha card background color.  What am I doing wrong?  Thank you for your help.

**Comment by j-a-n** [comment]
Wallpanel does not change anything in the dashboard (view).
Wallpanel is a screensaver that can also show cards on top of a image slideshow.
So you can add cards here:
```yaml
wallpanel:
  enabled: false
  idle_time: 0
  hide_toolbar: true
  hide_toolbar_action_icons: true
  hide_sidebar: true
  debug: false
  cards: <-----
    - type: weather-forecast
      entity: weather.home
```
