### ISSUE TITLE
Pull new image from unsplash

### ISSUE THREAD

**Issue by biofects** [j-a-n/lovelace-wallpanel#147]
Hello,
This is working great and thank you for this plugin.., However, is there a way that we can pull a new image from Unsplash at x time. Also I tried adding multiple search strings and it break wallpanel from starting 
This is my working config where images do not rotate:

```
wallpanel:
  enabled: true
  enabled_on_tabs: []
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: false
  display_time: 5
  image_url: https://source.unsplash.com/random/${1920}x${1080}?scenery
  info_animation_duration_x: 30
  info_animation_duration_y: 30
  cards:
    - type: weather-forecast
      entity: weather.forecast_tfam_home
      forecast_type: legacy
```

This is my config that will not rotate images but does not work with multiple search keywords:
```
wallpanel:
  enabled: true
  enabled_on_tabs: []
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: false
  display_time: 5
  image_url: https://source.unsplash.com/random/${1920}x${1080}?scenery,weather,landscape
  info_animation_duration_x: 30
  info_animation_duration_y: 30
  cards:
    - type: weather-forecast
      entity: weather.forecast_tfam_home
      forecast_type: legacy
```
