### ISSUE TITLE
`info-box-pos` is not reset when `info_move_interval` is turned off

### ISSUE THREAD

**Issue by Vitani** [j-a-n/lovelace-wallpanel#148]
# Reproduction Steps
1. Create a Text Input Helper called "broken_wallpanel"
2. Create a new dashboard and paste in the following config
```
wallpanel:
  enabled: true
  idle_time: 1
  display_time: 60
  image_url: https://picsum.photos/${width}/${height}?random=${timestamp}
  image_fit: cover
  image_list_update_interval: 3600
  info_move_pattern: random
  info_move_interval: 2
  profile_entity: input_text.broken_wallpanel
  profiles:
    fixed-position:
      info_move_interval: 0
  cards:
    - type: markdown
      content: >-
        Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin pulvinar
        pharetra sodales. Vivamus ligula magna, tristique vel vehicula vitae,
        sodales vel nulla. Maecenas luctus condimentum sapien sit amet interdum.
        Sed at augue ac lorem suscipit bibendum. Proin urna lacus, porttitor
        eget ex hendrerit, ornare aliquam velit. Quisque aliquet ex velit, et
        pharetra mi tempor auctor. Donec ut tincidunt lectus. Duis vel fringilla
        lacus. Nulla nec vestibulum est, a laoreet lectus. Nam feugiat euismod
        risus, nec convallis orci aliquam in.
views:
  - icon: mdi:home
    path: Home
    badges: []
    cards: []
```
3. Load the dashboard and note that after one second the wallpanel engages and the box of text will move around the screen - as expected
4. Change the value of `input_text.broken_wallpanel` to "fixed-position"
5. Note that the text will stop moving around the screen
6. Tap or mouse-over the dashboard to dismiss the screensaver
7. Wait one more second for the screensaver to re-engage
8. Note that the text is now positioned in the top left corner of the screen and (correctly) does not move around

# Expected Result

I would expect that when `info_move_interval` is changed to `0` by the _fixed-position_ profile that the position of the text would be reset back to the top left - as it is when the screensaver is re-engaged.

I believe this is caused by `div#wallpanel-screensaver-info-box-pos-y` and `div#wallpanel-screensaver-info-box-pos-x` not dismissing their custom styles.
