### ISSUE TITLE
Feature request: Fill black borders around the image pleasingly

### ISSUE THREAD

**Issue by j9brown** [j-a-n/lovelace-wallpanel#149]
I have my wall panel set up with a slideshow of family and vacation photos which have a variety of orientations and aspect ratios.  I use the 'contain' fill mode to ensure that folks' legs and heads don't get cropped (as would be the case with the 'cover' fill mode) but it often produces black borders.

Is there a way to fill these borders more pleasingly?

I've noticed that some media players fill black borders by placing the content on top of a blurred copy of the original or blurring and stretching out the sides.  These kinds of effects seem practical to do with a CSS filter but I don't know the right incantations or how to get it to play nice with the Ken Burns effect, etc.

Aside: I've seen some amazing examples of outpainting with artificial image generation but that seems rather out of scope for this request.  ;)

Thanks!

**Comment by j-a-n** [comment]
Nice idea, thanks!
Please try version 4.18.0.
You can play around with the following config:
```
wallpanel:
  image_background: image
  style:
    wallpanel-screensaver-image-background:
      filter: 'blur(15px)'
      background-position: center
      background-size: cover
```
