### ISSUE TITLE
Improve ken burns effect for wrong aspect-ratio pictures

### ISSUE THREAD

**Issue by amondit** [j-a-n/lovelace-wallpanel#158]
Hello,

Thanks again for having integrated the Ken Burns effect on pictures, it looks great and makes my HA dashboard look awesome while in simulated-screensaver mode!

One minor nitpick I have is that, for some pictures that are not in the right orientation (pictures in portrait displayed on a landscape dashboard, for example), they obviously get cropped (and sometimes not nicely, like faces being cut out, or unnecessary details get focused on), and that the ken burns effect could help with that if we could get it to 'pan' across the picture (instead of just select a part of the picture and zoom into it).

I know that's not an easy task to do, you might need to detect whether the picture is in landscape or portrait orientation and maybe adapt the css effect for it. However a quick search seems to get an example of someone that had the same kind of issue and managed to solve it by js/css: [stackoverflow thread](https://stackoverflow.com/questions/76477751/how-to-create-a-smooth-ken-burns-style-animation-using-transform-instead-of).

If you ever have some time to look into it it would be great :)

Thanks a lot!

**Comment by j-a-n** [comment]
Did you try `image_background: image` (see: #149)?

**Comment by amondit** [comment]
Well, it's not so much that I may want to display the full uncropped picture (with blurred background around), but instead change how the "start" and "end" zones of the ken burns effect to adapt to the aspect ratio of the picture. 
Kind of like this (how it's configured in iMovie): 
![image](https://github.com/j-a-n/lovelace-wallpanel/assets/2852406/a82659bc-1097-4476-b71a-1c51e7578a3b)
but, right now, it seems like the "end" zone is always contained inside the "start" zone. 
The idea would be to compute, based on the aspect ratio of the image and the aspect ratio of the display, how to do the animation. The problem is tackled in the stackoverflow post I linked earlier, but I don't know if any of the code in it could be applied here or not.

**Comment by andrewe24** [comment]
Echo Amondit 100%.  I understand the difficultly of very specific configuration both for the user and developer.  Maybe a simple configuration option would be pan versus zoom.  If pan is selected, the image is portrait, and the dashboard is landscape, then the image scrolls from top to bottom.  No background would need to be seen, but you still see the whole image with less-than-ideal cropping.

**Comment by j-a-n** [comment]
With version 4.47.0 I started to rework the Ken Burns effect implementation.
There is a new experimental config option `image_animation_ken_burns_animations` which can be used to select different animations. The default animation is named `simple`. Please try the new animations `experimental` and `experimental2`. I would be thankful to get some feedback.

Starting with version 4.47.0, the Ken Burns effect implementation is being reworked.
A new experimental configuration option, `image_animation_ken_burns_animations`, allows you to choose between different animation styles. The default animation is `simple`. Please try out the new animations `experimental` and `experimental2`.
Feedback is very welcome!

```yaml
wallpanel:
  image_fit_landscape: cover
  image_fit_portrait: cover
  image_animation_ken_burns_animations:
    - experimental
```

You can also play around with your own custom animations defined via `custom_css`:
```yaml
wallpanel:
  image_fit_landscape: cover
  image_fit_portrait: cover
  image_animation_ken_burns_animations:
    - custom1
  custom_css: |
        @keyframes kenBurnsEffect-custom1 {
            0% {
                transform: scale(1.0);
            }
            100% {
                transform: scale(calc(var(--ken-burns-zoom)));
            }
        }
```

These are the predefined animations:
```css
@keyframes kenBurnsEffect-experimental {
	0% {
		transform: scale(1.0) translateX(calc(var(--hidden-width) / -2 * 1px)) translateY(calc(var(--hidden-height) / -2 * 1px));
	}
	50% {
		transform: scale(var(--ken-burns-zoom));
	}
	90% {
		transform: scale(calc(1.0 + ((var(--ken-burns-zoom) - 1.0)/2))) translateX(calc(var(--hidden-width) / 2 * 1px)) translateY(calc(var(--hidden-height) / 2 * 1px));
	}
	100% {
		transform: scale(1.0);
	}
}
```
```css
@keyframes kenBurnsEffect-experimental2 {
	0% {
		transform: scale(1.0);
	}
	25% {
		transform: scale(calc(1.0 + ((var(--ken-burns-zoom) - 1.0)/2))) translateX(calc(var(--hidden-width) / 2 * 1px)) translateY(calc(var(--hidden-height) / 2 * 1px));
	}
	50% {
		transform: scale(var(--ken-burns-zoom));
	}
	75% {
		transform: scale(calc(1.0 + ((var(--ken-burns-zoom) - 1.0)/2))) translateX(calc(var(--hidden-width) / -2 * 1px)) translateY(calc(var(--hidden-height) / -2 * 1px));
	}
	100% {
		transform: scale(1.0);
	}
}
```
```css
@keyframes kenBurnsEffect-simple {
	0% {
		transform-origin: bottom left;
		transform: scale(1.0);
	}
	100% {
		transform: scale(var(--ken-burns-zoom));
	}
}
```
