### ISSUE TITLE
Feature request: second info box

### ISSUE THREAD

**Issue by kwithus** [j-a-n/lovelace-wallpanel#16]
I use an aloe iPad as Wallpanel, in portrait mode. My images for the screensaver are mostly landscape and I do use the setting of ‚scale-down‘
That gives me a black frame below and above the image, by that the info-box does not cover the image but is above in the black area. I do like this setting, as it shows a ‚slide-show‘ with additional basic HA Info above.
However, it would be nice to make use of the space below the image as well, for that a second info box would be nice.
Furthermore, would it be possible to get more than 3 rows for the grid or to use panel instead of grid for the info box? That would give some more flexibility in arranging the cards

**Comment by j-a-n** [comment]
You can add as many lines to the grid as you like.
Maybe you can play around with css margin:
```yaml
  cards:
    - type: markdown
      content: Card 1
      wp_style:
        width: 400px
        grid-row: 1
        grid-column: 1
    - type: markdown
      content: Card 2
      wp_style:
        width: 400px
        grid-row: 1
        grid-column: 2
    - type: markdown
      content: Card 3
      wp_style:
        width: 400px
        grid-row: 2
        grid-column: 1
        margin-top: 300px
    - type: markdown
      content: Card 4
      wp_style:
        width: 400px
        grid-row: 2
        grid-column: 2
        margin-top: 300px
```

**Comment by kwithus** [comment]
Sorry,  iced up columns and rows ;-). I would like to have more than 3 columns.

to get additional info at the bottom of the display, yes I could add additional rows (lines) however having yes row 1 and row 4 or 5 does not work, defining one card in row 1 and another in row 4 (without having any cards applied to row 2 ad 3 , will show the cards in row 1 and 2. Adding ‚empty‘ cards in between could probably work, however I don’t know what ccs would result in making those ‚blank‘ card invisible

**Comment by j-a-n** [comment]
You can have as many columns and rows as you like.
You can add a gap between the rows by setting `margin-top`.
Please try the following example:
```yaml
  cards:
    - type: markdown
      content: Card 1.1
      wp_style:
        width: 200px
        grid-row: 1
        grid-column: 1
    - type: markdown
      content: Card 1.2
      wp_style:
        width: 200px
        grid-row: 1
        grid-column: 2
    - type: markdown
      content: Card 1.3
      wp_style:
        width: 200px
        grid-row: 1
        grid-column: 3
    - type: markdown
      content: Card 1.4
      wp_style:
        width: 200px
        grid-row: 1
        grid-column: 4
    - type: markdown
      content: Card 2.1
      wp_style:
        width: 200px
        grid-row: 2
        grid-column: 1
        margin-top: 300px
    - type: markdown
      content: Card 2.2
      wp_style:
        width: 200px
        grid-row: 2
        grid-column: 2
        margin-top: 300px
```
