### ISSUE TITLE
Feature request: Stop screensaver on some event(Like MQTT)

### ISSUE THREAD

**Issue by rajuga153** [j-a-n/lovelace-wallpanel#167]
Hi,

Is it possible to add option to stop screensaver on some event like MQTT. My application is to stop screensaver on Video doorbell press and switch to Video doorbell Live Tab.

Thanks in advance...

Raju

**Comment by j-a-n** [comment]
Yes, you can start and stop the screensaver by using a boolean helper entity. See https://github.com/j-a-n/lovelace-wallpanel#screensaver_entity for details.

**Comment by rajuga153** [comment]
Hi,

Thanks for the prompt reply. I was looking for example code for same. But no luck and could not able to find same.
Could you please help me on same by sharing some example code.

**Comment by j-a-n** [comment]
What kind of sample code do you mean?
An automation?
You can create a boolean helper `input_boolean.wallpanel_screensaver` in HA settings.
Then use the following wallpanel configuration:
```yaml
wallpanel:
  screensaver_entity: input_boolean.wallpanel_screensaver
```
Then you can turn the screensaver on and off by toggling the state of the entity `input_boolean.wallpanel_screensaver` manually or by automation.

**Comment by rajuga153** [comment]
Hi,

After my previous post, I was able to create and use screensaver control by using automation.
Below is snapshot for my wallpanel config.
Now everything working fine as I expected. But courser move from one device is also interrupting other device screensaver operation. How to make it independent screensaver from each device?

wallpanel:
  enabled: false
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  image_fit: contain
  idle_time: 0
  display_time: 60
  image_animation_ken_burns: true
  image_order: random
  image_url: /local/Photos
  screensaver_stop_navigation_path: /lovelace/1
  screensaver_entity: input_boolean.wallpanel_control
  show_image_info: true

**Comment by j-a-n** [comment]
You can use different entities for different devices using the  [profile feature](https://github.com/j-a-n/lovelace-wallpanel#profiles):

```yaml
wallpanel:
  profiles:
    device_e9a2c86e_5526f1ee:
      screensaver_entity: input_boolean.screensaver_kitchen
    device_89ae788b_cd883eb1:
      screensaver_entity: input_boolean.screensaver_livingroom
```

**Comment by rajuga153** [comment]
Thanks for the clue but I could not be able understand on how to enable wallpanel for particular device and disable on others. I hope with profile we can not control "enabled" parameter.

Could you also help me to place "custom:digital-clock" card at bottom-left on screensaver?

Thanks,
Raju

**Comment by j-a-n** [comment]
To enable on selected devices only, you can use:
```yaml
wallpanel:
  enabled: false
  profiles:
    device_e9a2c86e_5526f1ee:
      enabled: true
    device_89ae788b_cd883eb1:
      enabled: true
```

**Comment by rajuga153** [comment]
Thanks for the example code. I appreciate your prompt support.

Could you also help me to place "custom:digital-clock" card at bottom-left on screensaver?

**Comment by j-a-n** [comment]
Please try:
```yaml
wallpanel:
  style:
    wallpanel-screensaver-info-box:
      margin-top: 'calc(100vh - 150px)'
```
