### ISSUE TITLE
local temperature entity

### ISSUE THREAD

**Issue by marcolega** [j-a-n/lovelace-wallpanel#18]
Is it possible to change weather temperature entity in order to use a local temperature sensor? 

br
Marco

**Comment by j-a-n** [comment]
You can use all the cards and badges that you can use in a dashboard.

For example:
```yaml
wallpanel:
  cards:
    - type: entity
      entity: sensor.local_temperature
```
