### ISSUE TITLE
Wallpanel stopped working

### ISSUE THREAD

**Issue by Gerritos2910** [j-a-n/lovelace-wallpanel#190]
Happy new year everyone. Knowing that this report might sound a but generic but after Wallpanel has worked fine for some weeks, it suddenly stopped showing pictures. Here is my code. I haven't changed anything besides normal updates (Wallpanel v4.23.2, HA-core updates).

I have already removed the code, refreshed, cleared browser cache and restarted HA. No improvements :-( Any ideas?

Thanks in advance!
```yaml
wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: false
  enabled_on_tabs:
    - Standard
  idle_time: 5
  display_time: 15
  keep_screen_on_time: 0
  black_screen_after_time: 90000000
  control_reactivation_time: 1
  image_url: /
  image_fit: contain
  image_list_update_interval: 3600
  image_order: random
  show_image_info: false
  cards: false
```

**Comment by j-a-n** [comment]
A happy new year to you too!
Please take a look at the browser console (F12).
Are there any error messages regarding wallpanel?
Any errors in HA logs?
Does it help to remove `enabled_on_tabs` from the config?

**Comment by Gerritos2910** [comment]
> A happy new year to you too! Please take a look at the browser console (F12). Are there any error messages regarding wallpanel? Any errors in HA logs? Does it help to remove `enabled_on_tabs` from the config?

Thanks a lot for your quick reply. No error messages in the browser console, no errors in HA logs. Removing the enabled_on_tabs also didn't work :-( I have deleted Wallpanel from HACS and re-installed (after HA-reboot and refresh of browser cache)

**Comment by j-a-n** [comment]
Does it work with a very simple configuration like the following?
```yaml
wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: false
  idle_time: 5
```
