### ISSUE TITLE
Wallpanel broke my HA

### ISSUE THREAD

**Issue by PrzemekSkw** [j-a-n/lovelace-wallpanel#195]
When I add that simple example in my raw editor I cannot do anything. Buttons/sliders don't response.

**Comment by j-a-n** [comment]
What device / browser are you using?

**Comment by njc88** [comment]
It's because this code hides the toolbar, sidebar and goes full screen. Probably not ideal as an example of code. 

```
wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
```
