### ISSUE TITLE
profile_entity is overwriting user based profile

### ISSUE THREAD

**Issue by imp3r4t0r** [j-a-n/lovelace-wallpanel#196]
Hello,

I have the following profile configuration:
```
  profiles:
    day:
      enabled: false
      idle_time: 60
      black_screen_after_time: 0
    night:
      enabled: false
      idle_time: 30
      black_screen_after_time: 60
    development:
      enabled: true
      idle_time: 5
      black_screen_after_time: 0
    user.ipad_9:
      enabled: true
      hide_sidebar: true
  profile_entity: input_select.wallpanel_profile
```

The `input_select.wallpanel_profile` is currently set to `day` and is set to `night` and to `day` again via automation on time base.

I would like to have different black_screen settings at day and at night and I also would like to have the whole wallpanel only be active on one specifiy iPad device. With the current `profile_entity: input_select.wallpanel_profile` enabled, all settings defined with `user.ipad_9` were overwritten and not been applied. If I remove the `profile_entity` line, then the user based settings ware applied, but the day and night settings were not applied anymore.

I assume that even with a user based profile, only one profile can be active at the same time. I was hoping that the use based profile is applied additionally to the none user base profile.

I there a chance in changing this behavior or do you have another idea, how to set up different time based setting on only one specifiy device?

Thanks a lot!
The wallpanel is insane btw!
