### ISSUE TITLE
Clock

### ISSUE THREAD

**Issue by cataseven** [j-a-n/lovelace-wallpanel#2]
Hi,

First of all, this is great work. Thank u. Can we only use real time clock and date as screensaver (digital / analog oprions maybe) ?

**Comment by j-a-n** [comment]
Hello,

please take a look at the newly released version 2.0.
Here you can add badges and cards on top of the images.
For example, you can use [custom:digital-clock](https://github.com/wassy92x/lovelace-digital-clock/).

You can use this config:

```yaml
wallpanel:
  enabled: true
  cards:
    - type: custom:digital-clock
      dateFormat:
        weekday: long
        day: 2-digit
        month: short
      timeFormat:
        hour: 2-digit
        minute: 2-digit
    - type: weather-forecast
      entity: weather.home
      show_forecast: true
      wp_style:
        padding-top: 10px
```
