### ISSUE TITLE
Browser crash 

### ISSUE THREAD

**Issue by w1tw0lf** [j-a-n/lovelace-wallpanel#205]
I have a raspberry pi 4 connected to a monitor that is running chrome in kiosk mode, displaying home assistant with wallpanel addon. It has been running perfectly for past couple of months without any issues. 

Since update yesterday to 2024.2 it keeps crashing the browser with

![image](https://github.com/j-a-n/lovelace-wallpanel/assets/55384762/69cb0b87-bc34-499c-8fd7-32cb12d80841)

I have re-installed os from scratch, used chromium, chromium-browser and firefox and still getting the error. Please advise if there is anything I can look at on the wallpanel addon.

**Comment by j-a-n** [comment]
Could be a memory problem.
Could you please monitor the memory usage?

**Comment by w1tw0lf** [comment]
Seems like you right, it starts with around 800mb ram usage and slowly creeps up to usage all memory and then the browser crashes with the error.

**Comment by j-a-n** [comment]
Is the memory usage only increasing with the wallpanel screensaver running?
What does your wallpanel configuration look like?

**Comment by j-a-n** [comment]
Could you please also take a look at the memory usage displayed by the Chrome task manager?

**Comment by w1tw0lf** [comment]
Same there, memory footprint slowly increases, until it  crashes.

**Comment by j-a-n** [comment]
How much memory usage is shown in the task manager? Could you please post your config?

**Comment by w1tw0lf** [comment]
Been playing around over the last few hours and it seems like it might be the cards that I am using causing the issue. Will keep posted if issue is resolved.

**Comment by w1tw0lf** [comment]
Recreated the cards on normal tab without wallpanel, made full screen and ran it for few hours, no increase on the memory usage. Also never crashed. Only thing that was mising is the background which I use google photos.

**Comment by j-a-n** [comment]
Perhaps you can find out which card is responsible for the memory increase. Then I can have a look at it.

**Comment by w1tw0lf** [comment]
It seems like the culpret could be mushroom cards. I have removed them and all seems fine now.

https://github.com/piitaya/lovelace-mushroom

**Comment by j-a-n** [comment]
Could you please add a sample wallpanel configuration with which I can reproduce the problem?

**Comment by w1tw0lf** [comment]
I did this as a test, to see 
```
wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  keep_screen_on_time: 0
  black_screen_after_time: 0
  image_url: media-entity://camera.google_photos_photo_frame_media
  show_image_info: false
  style:
    wallpanel-screensaver-info-box:
      '--wp-card-width': 457px
    wallpanel-screensaver-info-box-content:
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-border-width': 0px
      '--primary-text-color': '#e1e1e1'
      '--secondary-text-color': '#9b9b9b'
  cards:
    - entity: light.main_bedroom_lamp_left
      type: custom:mushroom-light-card
      layout: vertical
      name: Bedlamp Left    
      wp_style:
        grid-column: 1 / 1
        grid-row: 1 / 1
        background-color: '#00000099'
    - type: custom:button-card
      color_type: blank-card
      wp_style:
        grid-column: 2 / 2
        grid-row: 1 / 1
    - type: custom:button-card
      color_type: blank-card
      wp_style:
        grid-column: 3 / 3
        grid-row: 1 / 1
    - entity: light.main_bedroom_lamp_right
      type: custom:mushroom-light-card
      layout: vertical
      name: Bedlamp Left       
      wp_style:
        grid-column: 4 / 4
        grid-row: 1 / 1
        background-color: '#00000099'
views:
  - title: Home
    type: custom:grid-layout
    layout:
      gridrows: auto
      grid-template-columns: 25% 25% 25% 25%
      grid-template-areas: |
        "c1 c2 c3 c4"
    badges: []
    cards: []
```
If you keep an eye on either task manager in chrome or native you will see the memory slowly increase and the crashes chrome. It is definitely mushroom card relate. Have the wallpanel up and running for few days without issues.

**Comment by Vitani** [comment]
I also get this issue running a Tile card

This works fine (runs for hours):

```
views:
  - badges: []
    cards:
      - type: tile
        entity: sensor.time
```

This crashes after an hour or so:

```
wallpanel:
  enabled: true
  cards:
    - type: tile
      entity: sensor.time
views:
  - badges: []
    cards: []
```

If I change `type: tile` to `type: entity` it also works without any issue
