### ISSUE TITLE
Screen turns white on touch or mouse hover

### ISSUE THREAD

**Issue by attaxia** [j-a-n/lovelace-wallpanel#208]
When interacting with the dashboard, the screen turns white (and depending on settings displays the toolbar). It then fades back in about 30 sec later.
How can I prevent this?

I'm on Wallpanel 4.24 and Home Assistant 2024.2.1.

https://github.com/j-a-n/lovelace-wallpanel/assets/4743303/6b9921f2-a9f8-4761-899e-ac89b6e60a33

Config (still experimenting so may not make total sense)
```
wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: true
  fullscreen: false
  cards:
    - type: custom:alarmo-card
      entity: alarm_control_panel.alarmo
      button_scale_actions: 1
      button_scale_keypad: 1.4
      wp_style:
        grid-row: 1
        grid-column: 1
    - type: weather-forecast
      entity: weather.buienradar
      forecast_type: daily
      wp_style:
        width: 400px
        grid-row: 1
        grid-column: 2
    - type: entities
      entities:
        - sensor.solar_production
        - sensor.sonos_now_playing
        - sensor.mijnafvalwijzer_restafval
      wp_style:
        width: 400px
        grid-row: 2
        grid-column: 2
    - type: markdown
      content: Card 4
      wp_style:
        width: 400px
        grid-row: 3
        grid-column: 2
views:
  - title: Home
```

I've tried removeing the `views:` part but the YAML validator does not allow this.

**Comment by attaxia** [comment]
If I set `  idle_time: 0` the screen stays white indefinitely. Seems related to the screensaver function.

**Comment by j-a-n** [comment]
The "white screen" is the Lovelace Dashboard.
After the "idle time", the screen saver of the wallpanel starts.
The screensaver is then stopped again when you touch the screen.
If you do not want to display the dashboard at all and leave the screensaver running,
you can update to wallpanel version 4.24.1 and then add the following to your configuration:
```yaml
wallpanel:
  card_interaction: true
  stop_screensaver_on_mouse_click: false
  ...
```
