### ISSUE TITLE
Update screensaver-image immediately when changing to a profile with a different image_url

### ISSUE THREAD

**Issue by Vitani** [j-a-n/lovelace-wallpanel#212]
I've noticed that when changing between profiles that have different `image_url` settings (e.g. one set to 'picsum.photos', and another set to local media) the screensaver image doesn't immediately update, it waits until the `display_time` of the new profile is hit and then updates.

For example:

```
wallpanel:
  enabled: true
  display_time: 60
  image_url: https://picsum.photos/${width}/${height}?random=${timestamp}
  profiles:
    bins-out:
      image_url: /local/wallpanel/bins-out
      display_time: 10
```

Changing to profile to 'bins-out' can take up to 10 seconds to swap the picture, and changing the profile back to default can take up to 60.
