### ISSUE TITLE
Bug? "Event" opens behind wall panel when using built-in calendar card

### ISSUE THREAD

**Issue by sdholden28** [j-a-n/lovelace-wallpanel#214]
When using the code below, which is the "built-in" calendar card for HA, clicking on an event opens the larger event card behind wallpanel. So if I click an event in the calendar card, the "card_interaction" appears not to function, as nothing happens. When the screensaver is exited however, you see the larger event card on the dashboard behind wallpanel. So the "card_interaction" is functioning normally, but in the case of the calendar card, it opens behind wallpanel. I have tried numerous other cards in the same wallpanel config, and I have not seen this behavior anywhere else. It appears to be specific to the HA calendar card, which is fairly new. This is easily reproducable for me, so I would expect the issue to be global at the moment.

```
  card_interaction: true
  cards:
    - type: calendar
      initial_view: listWeek
      entities:
        - calendar.family
 ```
