### ISSUE TITLE
Center card in info box

### ISSUE THREAD

**Issue by theknut** [j-a-n/lovelace-wallpanel#221]
Is there a way to center the whole info box to the center of the screen?

**Comment by j-a-n** [comment]
You can try this:
```yaml
wallpanel:
  style:
    wallpanel-screensaver-info-box:
      margin: auto
```
