### ISSUE TITLE
Idle_time not respected in config

### ISSUE THREAD

**Issue by wormiedk** [j-a-n/lovelace-wallpanel#227]
I have the following in the top of my raw configuration editor:
```
wallpanel:
  enabled: false
  idle_time: 0
  hide_toolbar: false
  hide_sidebar: true
```
Whenever i enable wallpanel for a single page using the ?wp_enabled=true parameter the idle_time is not respected and the screen save still comes on. The only solution I have found is to set the idle tine to a very high number
