### ISSUE TITLE
Help - set font size

### ISSUE THREAD

**Issue by ceinmart** [j-a-n/lovelace-wallpanel#228]
Hi , 
I'm trying to set a bigger font size for a clock display, but it's limited to 48px / xxx-larger . 
I have no acknowledgment of CSS/HTML to solve this.. 
I've used the Markdown card , not sure if it's the best solution here.

Please, can give me a help how can I set this ? 

![image](https://github.com/j-a-n/lovelace-wallpanel/assets/7062410/b3872a79-853d-4431-95c9-2c3ea731c604)

```
wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  title: Casa DMartins
  idle_time: 10
  keep_screen_on_time: 1800
  black_screen_after_time: 0
  control_reactivation_time: 1
  screensaver_stop_navigation_path: /dashboard-wallpanel/0
  image_fit: scale-down
  image_url: media-entity://camera.google_photos_fotos_para_tv_media
  cards:
    - type: markdown
      content: |
        # <font size=8em>{{ states('sensor.hora')[0:5] }}</font>
        ## {{ states('sensor.data_br') }}
      show_header_toggle: false
      title: ' '
    - type: custom:weather-card
      entity: weather.casa_dmartins
      number_of_forecasts: '5'
    - type: custom:layout-card
      cards:
        - type: custom:mushroom-entity-card
          entity: sensor.sensor_temperatura_xiaomi_62_temperature
          name: Q. Augusto
        - type: custom:mushroom-entity-card
          entity: sensor.sensor_temperatura_xiaomi_b7_temperature
          name: Suite M.
        - type: custom:mushroom-entity-card
          entity: sensor.area_gourmet_temperatura
          name: Area Gourm.
        - type: custom:mushroom-entity-card
          entity: sensor.boiler_temperature
          name: Boiler
      columns: 2
      layout_type: custom:grid-layout
      layout:
        grid-template-columns: auto
        grid-template-areas: |
          "lin1 lin1 "
        mediaquery:
          '(max-width: 800px)':
            grid-template-columns: 50% 50%
            grid-template-areas: |
              "lin1 lin1"
              "lin1 lin1"
              "lin1 lin1"
              "lin1 lin1"
      view_layout:
        grid-area: cab1
  info_move_fade_duration: 2
  image_list_update_interval: 30
  image_order: random
  show_image_info: false
  fetch_address_data: false
  screensaver_entity: input_boolean.wallpanel_screensaver
  card_interaction: true
  style:
    wallpanel-screensaver-container:
      background-color: '#333333dd'
    wallpanel-screensaver-info-box:
      '--wp-card-width': 350px
      background-color: '#00000050'
      box-shadow: >-
        0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0,
        0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12)
    wallpanel-screensaver-info-box-content:
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-border-width': 0px
      '--primary-background-color': '#fafafa'
      '--secondary-background-color': '#e5e5e5'
      '--primary-text-color': '[#212121](https://github.com/j-a-n/lovelace-wallpanel/issues/212121)'
      '--secondary-text-color': '[#727272](https://github.com/j-a-n/lovelace-wallpanel/issues/727272)'
```

**Comment by j-a-n** [comment]
Hi,

you can use this:
```yaml
    - type: markdown
      content: |
        # {{ states('sensor.hora')[0:5] }}
        ## {{ states('sensor.data_br') }}
      show_header_toggle: false
      title: ' '
      wp_style:
        font-size: 3em
```
