### ISSUE TITLE
Wallpanel only shows one picture all the time

### ISSUE THREAD

**Issue by Bias84** [j-a-n/lovelace-wallpanel#229]
After the Image-Rotation was not working as metioned the last month, i tried to put in some new categories.

Wallpanel was only showing pictures from two oder maybe three of the categories.

Now Wallpanel ist only showing one and the same picture all the time... :(

My working code for so long:

  image_url: >-
    https://source.unsplash.com/random/${1920}x${1080}?naturbilder,sonnenlicht,wanderlust,love,dog,spring,summer,weather,mountain,lake,flowers,home,tirol&sig=${timestamp}
  image_fit: cover
  image_list_update_interval: 3600
  show_progress_bar: true

**Comment by j-a-n** [comment]
This seem to be an unsplash issue.
Try to remove some keywords.
You can also switch to the new Unsplash API: https://github.com/j-a-n/lovelace-wallpanel#http-url
Also keep `${width}x${height}` in the URL, wallpanel will replace this with the current screen resolution.
This configuration seems to work:
```yaml
wallpanel:
  image_url: "https://source.unsplash.com/random/${width}x${height}?sonnenlicht,sonnenlicht,wanderlust,love,dog,spring,summer,weather,mountain,lake,flowers,home,tirol&sig=${timestamp}"
  image_fit: cover
  show_progress_bar: true
```
