### ISSUE TITLE
synology as media source

### ISSUE THREAD

**Issue by xgaibtcgd** [j-a-n/lovelace-wallpanel#242]
Hello,

I'm trying to set this up for the first time but it doesn't use any of the synology albums I specify.  Any idea where i'm going wrong? I can see the album in home assistant media source.

`title: Calendar
path: full-screen
panel: true
cards:
  - type: iframe
    url: https://dakboard.com/screen/uuid/6
    aspect_ratio: "16:9"
    image_order: random
    image_list_update_interval: 3600
    image_url: media-source://synology_dsm/21524R0WJBV/2
`

**Comment by xgaibtcgd** [comment]
Sorry pretty new to this, i see my error :)

**Comment by j-a-n** [comment]
Hello,
you have to add the wallpanel configuration at the very beginning of the yaml configuration.

```yaml
wallpanel:
  enabled: true
  image_order: random
  image_list_update_interval: 3600
  image_url: media-source://synology_dsm/21524R0WJBV/2

title: Calendar
...
```
