### ISSUE TITLE
how to remove border

### ISSUE THREAD

**Issue by kejeva** [j-a-n/lovelace-wallpanel#244]
need help, how i can remove the border ?

here my code:
```yaml
wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: true
  idle_time: 1
  info_animation_duration_x: 30
  cards:
    - type: vertical-stack
      cards:
        - type: custom:weather-card
          details: true
          forecast: true
          hourly_forecast: false
          name: Weather
          entity: weather.kejeva_home
          current: true
          number_of_forecasts: '6'
        - type: custom:sun-card
          darkMode: true
          showAzimuth: true
          showElevation: true
  style:
    wallpanel-screensaver-container:
      background-color: '#333333dd'
    wallpanel-screensaver-info-box:
      '--wp-card-width': 450px
      background-color: '#ffffff99'
      box-shadow: >-
        0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0,
        0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12)
    wallpanel-screensaver-info-box-content:
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-box-border': none
      '--primary-background-color': '#fafafa'
      '--secondary-background-color': '#e5e5e5'
      '--primary-text-color': '#212121'
      '--secondary-text-color': '#727272'
```
![Uploading screen.png…]()

**Comment by j-a-n** [comment]
There is no image attached.

**Comment by kejeva** [comment]
![screen](https://github.com/j-a-n/lovelace-wallpanel/assets/67554074/dbb662be-3c1d-4a61-8a41-3ab2d1bec7c8)

Sorry...here the picture

**Comment by j-a-n** [comment]
Not sure which border you mean.
Please try:
```yaml
wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: true
  idle_time: 1
  info_animation_duration_x: 30
  cards:
    - type: vertical-stack
      cards:
        - type: custom:weather-card
          details: true
          forecast: true
          hourly_forecast: false
          name: Weather
          entity: weather.kejeva_home
          current: true
          number_of_forecasts: '6'
        - type: custom:sun-card
          darkMode: true
          showAzimuth: true
          showElevation: true
  style:
    wallpanel-screensaver-container:
      background-color: '#333333dd'
    wallpanel-screensaver-info-box:
      '--wp-card-width': 450px
      background-color: '#ffffff00'
      box-shadow: none
    wallpanel-screensaver-info-box-content:
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-box-border': none
      '--primary-background-color': '#fafafa'
      '--secondary-background-color': '#e5e5e5'
      '--primary-text-color': '#212121'
      '--secondary-text-color': '#727272'
```

**Comment by kejeva** [comment]
sorry, any other way, already try, but the border still exist
![wall](https://github.com/j-a-n/lovelace-wallpanel/assets/67554074/db6430b3-c992-4a65-882d-82bd962a5322)

**Comment by j-a-n** [comment]
This should work:
```yaml
wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: true
  idle_time: 1
  info_animation_duration_x: 30
  cards:
    - type: vertical-stack
      cards:
        - type: custom:weather-card
          details: true
          forecast: true
          hourly_forecast: false
          name: Weather
          entity: weather.kejeva_home
          current: true
          number_of_forecasts: '6'
        - type: custom:sun-card
          darkMode: true
          showAzimuth: true
          showElevation: true
  style:
    wallpanel-screensaver-container:
      background-color: '#333333dd'
    wallpanel-screensaver-info-box:
      '--wp-card-width': 450px
      background-color: '#ffffff00'
      box-shadow: none
    wallpanel-screensaver-info-box-content:
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-box-border': none
      '--ha-card-border-width': 0px
      '--primary-background-color': '#fafafa'
      '--secondary-background-color': '#e5e5e5'
      '--primary-text-color': '#212121'
      '--secondary-text-color': '#727272'
```
