### ISSUE TITLE
Black Screen at night, user defined wallpanel when someone is home

### ISSUE THREAD

**Issue by kobraevents** [j-a-n/lovelace-wallpanel#252]
First: Very cool project! I love it and using it since a year.

What i like is to set a time-scheduler in wich the wallpanel is working.
For example: betwenn 8am and 10pm the wallpanel is showing pictures, oterhwise it shows a black screen.
Also for my parents i need a way to set wallpanel active when some is home. Tracking the mobile phone is not the problem.

i know there is a boolean which one can set enabled or disabled and the wallpanel starts its routine but its not what iam looking for. on the devices of my parents and grandma i cant run kiosk, so i need to modify the "black_screen_after_time" ?! how can i do it?

creating an automation is simple but how to get wallpanel to show black screen.

**Comment by j-a-n** [comment]
Hello,
you can use [profiles](https://github.com/j-a-n/lovelace-wallpanel?tab=readme-ov-file#profiles) for that.
```yaml
  profiles:
    day:
      black_screen_after_time: 0
    night:
      black_screen_after_time: 60
  profile_entity: input_select.wallpanel_profile
```
