### ISSUE TITLE
Screensaver Won't Display Without True in URL After HA Core Update

### ISSUE THREAD

**Issue by klaw333** [j-a-n/lovelace-wallpanel#254]
On v4.25.4 with 2024.6.4

After updating to 2024.6.4 the screensaver will only show if I add ?wp_enabled=true to the end of my URL. Even a very basic dashboard like below won't work without true in the url. If I revert the core update it works like normal again.

```yaml
views:
  - title: test
    wallpanel:
      enabled: true
      hide_toolbar: true
      hide_sidebar: true
      fullscreen: true
      idle_time: 2
```

**Comment by j-a-n** [comment]
The wallpanel configuration must be inserted at the top:
```yaml
  wallpanel:
    enabled: true
    hide_toolbar: true
    hide_sidebar: true
    fullscreen: true
    idle_time: 2
views:
  - title: test
```
