### ISSUE TITLE
Mixing username profile and input_select does not work

### ISSUE THREAD

**Issue by aqwserf** [j-a-n/lovelace-wallpanel#255]
Hi,
Following the example [here](https://github.com/j-a-n/lovelace-wallpanel?tab=readme-ov-file#profiles), I'm trying to mix a username based profile (for test purposes) and automatic day/night profile for my tablet. However, mixing both doesn't allow me to have the profile with the user's name, only the one based on the input_select.
Here's the snippet:
```yaml
wallpanel:
  show_images: false
  style:
    wallpanel-screensaver-info-box:
      '--wp-card-width': 450px
      background-color: '#00000099'
      box-shadow: >-
        0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0,
        0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12)
    wallpanel-screensaver-info-box-content:
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-border-width': 0px
      '--primary-background-color': '#111111'
      '--secondary-background-color': '#202020'
      '--primary-text-color': '#e1e1e1'
      '--secondary-text-color': '#9b9b9b'
  cards:
    - type: custom:clock-weather-card
 ...
  profiles:
    user.aqwserf:
      enabled: false
      hide_toolbar: false
      hide_toolbar_action_icons: false
      hide_sidebar: false
      fullscreen: false
    kiosk_day:
      enabled: true
      hide_toolbar: true
      hide_toolbar_action_icons: true
      hide_sidebar: true
      fullscreen: true
      idle_time: 60
      keep_screen_on_time: 0
      black_screen_after_time: 0
    kiosk_night:
      enabled: true
      hide_toolbar: true
      hide_toolbar_action_icons: true
      hide_sidebar: true
      fullscreen: true
      idle_time: 5
      keep_screen_on_time: 5
      black_screen_after_time: 6
  profile_entity: input_select.kiosk_mode
```

Using my tablet with the user `kiosk`, it's working as expected (`kiosk_day`/`kiosk_night)`. However, using a computer with the user `Aqwserf`, it also uses the profile from the `input_select.kiosk_mode` and does not take into account the username based profile.
I've tried in a private window, refresh the page, no way to make it work.
Did I understand the example correctly?  Who has priority when several profile types are available?

Thanks!

[EDIT] I've also tried with an `input_text.kiosk_mode` without success

**Comment by SebastiaanVBH** [comment]
Are you using the Username or Display name?
I wanted to be able to edit the dashboard from my "admin" user which didn't work for a while as well. Then I used the display name and that does work!

Display name                                   username
Me Myself And I                              admin

Instead of using:
user.admin

Use this:
user.me_myself_and_i

**Comment by aqwserf** [comment]
I'm using the display name lower case. You made me doubt it, but it could have been :)
I tried to use this trick to avoid draining the battery (that doesn't really last) but I ended up using ssh command to kill/start HA based on motion. I works well so I got rid of this profile based configuration.
So I guess I can close this issue unless someone as the exact issue.

**Comment by wmtech-1** [comment]
@aqwserf This does work as expected. The correct code for your purpose would be:

```
wallpanel:
  show_images: false
  style:
    wallpanel-screensaver-info-box:
      '--wp-card-width': 450px
      background-color: '#00000099'
      box-shadow: >-
        0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0,
        0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12)
    wallpanel-screensaver-info-box-content:
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-border-width': 0px
      '--primary-background-color': '#111111'
      '--secondary-background-color': '#202020'
      '--primary-text-color': '#e1e1e1'
      '--secondary-text-color': '#9b9b9b'
  cards:
    - type: custom:clock-weather-card
 ...
  profiles:
    user.aqwserf:
      enabled: false
      hide_toolbar: false
      hide_toolbar_action_icons: false
      hide_sidebar: false
      fullscreen: false
      profile_entity: input_select.kiosk_mode
      profiles:
        kiosk_day:
          enabled: true
          hide_toolbar: true
          hide_toolbar_action_icons: true
          hide_sidebar: true
          fullscreen: true
          idle_time: 60
          keep_screen_on_time: 0
          black_screen_after_time: 0
        kiosk_night:
          enabled: true
          hide_toolbar: true
          hide_toolbar_action_icons: true
          hide_sidebar: true
          fullscreen: true
          idle_time: 5
          keep_screen_on_time: 5
          black_screen_after_time: 6
```
