### ISSUE TITLE
[BUG] wallpanel stop working after refresh page

### ISSUE THREAD

**Issue by kaanvur** [j-a-n/lovelace-wallpanel#258]
Hello,
I created a new dashboard and made the settings as shown.
I tried it on an old phone that I wanted to use as a dashboard.
It actually works without any problems. But whenever I refresh the page or exit and enter again, wallpanel stops working.
When I enter edit in the dashboard and save the settings again, it works.
These are my dashboard settings. I don't know where the problem is

```
wallpanel:
  enabled: true
  idle_time: 10
  card_interaction: true
  cards:
    - type: custom:clock-weather-card
      entity: weather.home
      wp_style:
        width: calc(45vw - 40px)
        grid-column: 1
        '--ha-card-background': rgba(0, 0, 0, 0.4)
    - type: vertical-stack
      cards:
        - type: custom:slider-button-card
          entity: light.office
          slider:
            direction: left-right
            background: gradient
            use_state_color: false
            use_percentage_bg_opacity: false
            show_track: false
            toggle_on_click: false
            force_square: false
            show_attribute: false
          show_name: true
          show_state: true
          compact: true
          icon:
            show: true
            use_state_color: true
            tap_action:
              action: more-info
            icon: ''
          action_button:
            mode: custom
            icon: mdi:power
            show: true
            show_spinner: true
            tap_action:
              action: toggle
          show_attribute: true
        - type: custom:slider-button-card
          entity: light.yeelink_lamp4_489f_light
          name: Desk Lamp
          slider:
            direction: left-right
            background: gradient
            use_state_color: true
            use_percentage_bg_opacity: false
            show_track: false
            toggle_on_click: false
            force_square: false
            show_attribute: false
          show_name: true
          show_state: true
          compact: true
          icon:
            show: true
            use_state_color: true
            tap_action:
              action: more-info
            icon: ''
          action_button:
            mode: custom
            icon: mdi:power
            show: true
            show_spinner: true
            tap_action:
              action: toggle
          show_attribute: true
        - type: custom:mushroom-entity-card
          entity: switch.desk_socket_1
          name: Desk Switch
          tap_action:
            action: toggle
        - type: custom:mushroom-entity-card
          entity: switch.pc_socket_1
          name: PC Switch
          tap_action:
            action: toggle
        - type: custom:mushroom-entity-card
          entity: switch.office_motion_sensor_motion_sensor_enabled
          name: Office motion sensor
          tap_action:
            action: toggle
      wp_style:
        width: calc(30vw - 40px)
        grid-column: 2
        '--ha-card-background': rgba(0, 0, 0, 0.4)
strategy:
  type: custom:mushroom-strategy
  options:
    home_view:
      hidden:
        - greeting
        - areasTitle
        - persons
views: []

```
