### ISSUE TITLE
EXIF location

### ISSUE THREAD

**Issue by kwithus** [j-a-n/lovelace-wallpanel#26]
I think it’s a very good idea to enable showing EXIF data, Actually something I was already going to ask for.
However, can you provide an example how to show the location, the image was taken at? (or is that an additional request?)
I tried to find out but was unable to succeed.

**Comment by j-a-n** [comment]
The EXIF data contains only GPS coordinates.
You will need an geocoding API to convert that to a location name. I am working on that.

**Comment by kwithus** [comment]
perfekt! I already assumed that there is a need to ‚translate‘ the GPS Data.
will be a very nice addition to your wallpaper.
maybe (if possible) with an option to show either complete adress or just country or country and town/area

Von meinem iPhone gesendet

**Comment by j-a-n** [comment]
Please have a look at the changes in version 3.1.
You can start with the following configuration:
```yaml
wallpanel:
  show_exif_info: true
  fetch_address_data: true
  exif_info_template: '${address.town!suffix= // }${DateTimeOriginal}'
```
