### ISSUE TITLE
[FEATURE REQUEST] Add ability to center and scale infobox

### ISSUE THREAD

**Issue by DragonHunter274** [j-a-n/lovelace-wallpanel#270]
I use this on a very small screen where the infobox uses up the entire size of the screen.
It would be great if it was possible to center it.  It would also be great if it was possible to scale the infobox contents to be able to fit more cards onto the screen

EDIT: tried margin: auto as described in a different issue but couldn't get it to work

**Comment by j-a-n** [comment]
You can use CSS to achieve this.
For example:
```yaml
  style:
    wallpanel-screensaver-info-box:
      margin: auto
      transform: scale(2.5)
```
