### ISSUE TITLE
enabled on tabs does not work

### ISSUE THREAD

**Issue by forfeitjunk** [j-a-n/lovelace-wallpanel#280]
This is my config below

once I use the enabled_on_tabs function the screensaver does not start.

```yaml
views:
  - title: Home
wallpanel:
  enabled: true
  enabled_on_tabs:
    - default_view
  debug: false
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: false
  idle_time: 10
  screensaver_stop_navigation_path: /lovelace/default_view
  image_url: media-source://media_source
  image_fit: cover
```
