### ISSUE TITLE
MQTT works only one way

### ISSUE THREAD

**Issue by Aixx1** [j-a-n/lovelace-wallpanel#283]
I have an Android (Go edition) device and it's successfully passing on its sensor data to HA, but cannot communicate from HA to the Device. I can see the messages going through in MQTT Explorer though.

```
action: mqtt.publish
data:
  qos: "1"
  payload: "{\"wake\": true, \"wakeTime\": 180}"
  topic: wallpanel/mywallpanel
  evaluate_payload: true
  retain: false
```

I tried also with `payload: '{"wake": true, "wakeTime": 180}'`, also with different commands like 'brightness' etc. Tried 'topic: wallpanel/mywallpanel', 'topic: wallpanel/mywallpanel/', 'topic: wallpanel/mywallpanel/wake' etc. but the phone doesn't wake up. Tried mostly while the screensaver was active, but also while screen turned off from the power button.
Is there a log for WallPanel somewhere?
Amazing app, thanks!<3
