### ISSUE TITLE
How to target badges div for CSS style / layout

### ISSUE THREAD

**Issue by apiontek** [j-a-n/lovelace-wallpanel#288]
With Wall Panel 4.29.1 on HA 2024.10.0 (frontend 20241002.2), I'm trying to produce a grid layout like

<table>
  <tr>
    <td colspan="2">badges (centered)</td>
  </tr>
  <tr>
    <td>card 1</td>
    <td>card 2</td>
  </tr>
</table>

But I can't figure out how to target the `div.badges` with grid style. I see that I can target individual badges with `wp_style` but for the above I need to target their container.

As an alternative, I could potentially work with:

<table>
<tr>
<td>badges</td>
<td rowspan="2">card 2</td>
</tr>
<tr><td>card 1</td></tr>
</table>

...except "card 2" is much taller than "badges" and "card 1" combined, and there ends up being unwanted space between "badges" and "card 1" — basically like this:

<table>
<tr>
<td>badges</td>
<td rowspan="4">card 2</td>
</tr>
<tr>
  <td>·</td>
</tr>
<tr>
  <td>card 1</td>
</tr>
<tr>
  <td>·</td>
</tr>
</table>

And I think I can also only fix this by targeting `div.badges` with CSS, so I'm back to square one.

Is there a way to do this?

**Comment by j-a-n** [comment]
Hi,
just added the ability to style the badges div with version 4.30.0.
You can now use something like:
```yaml
wallpanel:
  cards:
    - type: markdown
      content: Card 1
      wp_style:
        grid-row: 2
        grid-column: 1
    - type: markdown
      content: Card 2
      wp_style:
        grid-row: 2
        grid-column: 2
  style:
    wallpanel-screensaver-info-box:
      margin: auto
    wallpanel-screensaver-info-box-badges:
      grid-row: 1
      grid-column: 1 / span 2
```
