### ISSUE TITLE
[FR] Profile per user

### ISSUE THREAD

**Issue by SendNukez** [j-a-n/lovelace-wallpanel#29]
I love the screensaver on my wallpanels, but on my phone / pc it gets quite annoying. I have tried to code a per-user profile function myself but it didn't work fully. My idea was to set `profile_entity` to `user` and this would set the profile based on the current user (I got it using `elHass.__hass.user.name.toLowerCase()`). so I could then do per-user profiles by just using the normal `profiles` config option. I tried to disable the screensaver by default and only enable it for certain profiles, which didn't work. I'm guessing if `enabled` is set to false it doesn't even check for profiles and is just completely disabled.

**Comment by kwithus** [comment]
I haven’t tried it myself, but in the installation guidance you’ll find guidelines to
“Activate on individual devices only”
Which should address what you want

**Comment by SendNukez** [comment]
Yeah, I tried that. But some navigation links remove the query params.

**Comment by j-a-n** [comment]
Hi!
I just released version 3.2 with support for user profiles.
You can easily add a profile for a user which will be activated automatically if the username matches:
```yaml
wallpanel:
  profiles:
    user.foo:
      enabled: false
```

**Comment by pacmac** [comment]
I know this issue is closed, but this will not work for me:

```
wallpanel:
  enabled: false
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  cards:
    - type: weather-forecast
      entity: weather.openweathermap
      show_forecast: true
  profiles:
    user.nspp:
      enabled: true
    user.pac:
      enabled: true
```

This does not activate wallpanel for those user IDs.
