### ISSUE TITLE
browser-mod integration issue

### ISSUE THREAD

**Issue by ursnirmalt** [j-a-n/lovelace-wallpanel#293]
```
Profiles:
    device.Chrome-LTDVE071:
      image_url: media-source://media_source/local/FamilyLandscape/
      screensaver_entity: input_boolean.screensaver_Chrome-LTDVE071
    device.basementcmpedge:
      image_url: media-source://media_source/local/FamilyPortrait/
      screensaver_entity: input_boolean.screensaver_basementcmpedge
```
this is my code. I am getting default pictures from internet. it is not loading from local media source. 

Chrome-LTDVE071 is my browserid for one of the device and basementcmpedge is another device.
