### ISSUE TITLE
Using Wallpanel & Browser Mod for individual devices

### ISSUE THREAD

**Issue by AdmiralRaccoon** [j-a-n/lovelace-wallpanel#298]
Hello there and thanks for the nice addon.
I was trying to use the individual device function, but I can´t get it work on a Windows nor on an Android device 
I just want to hide the toolbar on this specific device - is the formatting wrong?

```
wallpanel:
  enabled: false
  device.tablet_da7fcded:
    enabled: true
    hide_toolbar: true
    keep_screen_on_time: 0
    show_images: false 
```

Thank you,
Philipp
