### ISSUE TITLE
Wallpanel not triggering since 2024.10.4

### ISSUE THREAD

**Issue by SauRoNZA** [j-a-n/lovelace-wallpanel#300]
This is probably something fundamentally stupid but Wallpanel is simply not starting since I upgraded Home Assistant to the latest version (and possibly the version before that) and since I see nobody complaining about this it must be a me problem.

Nothing in my configuration was changed, but possibly something is no longer supported causing the problem.

*Apparently Github doesn't like code snippets and doesn't do indenting properly, but that is correct and my configuration passes.
```
wallpanel:

  badges:
    - entity: person.*
    - entity: sensor.*
    - entity: sensor.*
    - entity: person.*
    - entity: sensor.*
    - entity: sensor.*
  enabled: true
  idle_time: 60
  info_animation_duration_x: 10
  info_animation_duration_y: 20
  info_animation_timing_function_x: steps(3, end)
  info_animation_timing_function_y: steps(3, end)
  style: null
  wallpanel-screensaver-info-box:
    '--wp-card-width': 450px
  wallpanel-screensaver-info-box-content:
    '--ha-card-background': none
    '--ha-card-box-shadow': none
    '--ha-card-border-width': 0px
    text-shadow: >-
      -0.5px -0.5px 0 rgb(17, 17, 17), 0.5px -0.5px 0 rgb(17, 17, 17), -0.5px
      0.5px 0 rgb(17, 17, 17), 0.5px 0.5px 0 rgb(17, 17, 17)
    '--primary-text-color': '#ffffff'
    '--secondary-text-color': '#dddddd'
  type: horizontal-stack
  cards:
    - type: custom:clock-weather-card
      entity: weather.home
      wp_style:
        width: 400px
        height: 320px
        grid-row: 1
        grid-column: 1
    - type: gauge
      entity: sensor.geyser_temperature
      max: 60
      needle: true
      name: Geyser
      severity:
        green: 25
        yellow: 0
        red: 50
      min: 15
      wp_style:
        width: 400px
        grid-row: 2
        grid-column: 2
    - type: custom:atomic-calendar-revive
      enableModeChange: true
      firstDayOfWeek: 1
      refreshInterval: 1800
      entities:
        - calendar.family
        - calendar.personal
        - calendar.*
        - calendar.*
      showCurrentEventLine: false
      showMonth: false
      showWeekDay: true
      disableEventLink: true
      showNoEventsForToday: false
      disableLocationLink: false
      showFullDayProgress: false
      showEventIcon: false
      showHiddenText: false
      showCalendarName: true
      calShowDescription: false
      showLastCalendarWeek: true
      disableCalEventLink: false
      disableCalLocationLink: false
      disableCalLink: true
      showDescription: false
      dateFormat: LL
      showDate: false
      sortByStartTime: false
      showRelativeTime: true
      showProgressBar: true
      showLocation: true
      showDeclined: true
      showMultiDayEventParts: false
      showMultiDay: true
      showLoader: false
      maxDaysToShow: 5
      dimFinishedEvents: true
      hideDuplicates: true
      hideFinishedEvents: true
      showWeekNumber: false
      showEventDate: true
      showTimeRemaining: true
      showDatePerEvent: false
      showAllDayHours: false
      hoursOnSameLine: false
      compactMode: false
      showAllDayEvents: true
      defaultMode: Event
      wp_style:
        width: 400px
        grid-row: 1
        grid-column: 2
    - type: custom:sunsynk-power-flow-card
      wp_style:
        width: 400px
        grid-row: 1
        grid-column: 3
      cardstyle: lite
      panel_mode: true
      show_solar: true
      inverter:
        modern: true
        colour: black
        auto_scale: true
      battery:
        energy: 19200
        shutdown_soc: 15
        invert_power: false
        colour: red
        show_daily: true
        auto_scale: true
        show_remaining_energy: true
        dynamic_colour: true
        linear_gradient: false
      solar:
        colour: orange
        show_daily: true
        mppts: 2
        auto_scale: true
        dynamic_colour: true
        display_mode: 2
      load:
        colour: green
        show_daily: true
        show_aux: false
        invert_aux: false
        auto_scale: true
        dynamic_colour: true
        dynamic_icon: true
      grid:
        colour: blue
        no_grid_colour: null
        show_daily_buy: true
        show_daily_sell: false
        show_nonessential: false
        auto_scale: true
      entities:
        essential_power: sensor.load_power
        use_timer_248: switch.toggle_system_timer
        priority_load_243: switch.toggle_priority_load
        inverter_voltage_154: sensor.ss_inverter_voltage
        load_frequency_192: sensor.ss_inverter_frequency
        inverter_current_164: sensor.ss_inverter_current
        inverter_power_175: sensor.inverter_power
        grid_connected_status_194: binary_sensor.grid_online
        inverter_status_59: sensor.overall_state
        day_battery_charge_70: sensor.ss_day_battery_charge
        day_battery_discharge_71: sensor.ss_day_battery_discharge
        battery_voltage_183: sensor.battery_voltage
        battery_soc_184: sensor.battery_soc
        battery_power_190: sensor.battery_power
        battery_current_191: sensor.ss_battery_current
        grid_power_169: sensor.grid_inverter_load
        day_grid_import_76: sensor.ss_day_grid_import
        day_grid_export_77: sensor.ss_day_grid_export
        grid_ct_power_172: sensor.grid_power
        day_load_energy_84: sensor.ss_day_load_energy
        day_pv_energy_108: sensor.ss_day_pv_energy
        pv1_power_186: sensor.pv1_power
        pv1_voltage_109: sensor.ss_pv1_voltage
        pv1_current_110: sensor.ss_pv1_current
        pv2_voltage_111: sensor.ss_pv2_voltage
        pv2_current_112: sensor.ss_pv2_current
        remaining_solar: sensor.energy_production_today_remaining
        battery_temp_182: sensor.battery_temperature
        radiator_temp_91: sensor.ss_radiator_temperature
        dc_transformer_temp_90: sensor.ss_dc_transformer_temperature
        pv2_power_187: sensor.ss_pv2_power
      large_font: true
      show_battery: true
      show_grid: true
    - type: gauge
      wp_style:
        width: 400px
        grid-row: 2
        grid-column: 3
      entity: sensor.prepaid_units_left_2
      min: 0
      max: 200
      name: Prepaid Balance
      severity:
        green: 50
        yellow: 25
        red: 10
```

**Comment by SauRoNZA** [comment]
Okay seems re-ordering things so the main enable and idle values sit above badges and removing the style: null value fixed it. 

Also modes the entire thing to the top of my RAW config which I only spotted in the documentation for the first time now.

**Comment by SauRoNZA** [comment]
Okay seems re-ordering things so the main enable and idle values sit above badges and removing the style: null value fixed it.

Also modes the entire thing to the top of my RAW config which I only spotted in the documentation for the first time now.

**Comment by j-a-n** [comment]
This part of the config seems to be invalid:
```yaml
  style: null
  wallpanel-screensaver-info-box:
    '--wp-card-width': 450px
  wallpanel-screensaver-info-box-content:
    '--ha-card-background': none
    '--ha-card-box-shadow': none
    '--ha-card-border-width': 0px
    text-shadow: >-
      -0.5px -0.5px 0 rgb(17, 17, 17), 0.5px -0.5px 0 rgb(17, 17, 17), -0.5px
      0.5px 0 rgb(17, 17, 17), 0.5px 0.5px 0 rgb(17, 17, 17)
    '--primary-text-color': '#ffffff'
    '--secondary-text-color': '#dddddd'
  type: horizontal-stack
  cards:
    - type: custom:clock-weather-card
      entity: weather.home
```
Please try:
```yaml
  style:
    wallpanel-screensaver-info-box:
      '--wp-card-width': 450px
    wallpanel-screensaver-info-box-content:
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-border-width': 0px
      text-shadow: >-
        -0.5px -0.5px 0 rgb(17, 17, 17), 0.5px -0.5px 0 rgb(17, 17, 17), -0.5px
        0.5px 0 rgb(17, 17, 17), 0.5px 0.5px 0 rgb(17, 17, 17)
      '--primary-text-color': '#ffffff'
      '--secondary-text-color': '#dddddd'
  cards:
    - type: custom:clock-weather-card
      entity: weather.home
```
Please have a look at the browser console (F12).
Are there any error messages regarding wallpanel?
