### ISSUE TITLE
Goes back and forth between just two images

### ISSUE THREAD

**Issue by johnsturgeon** [j-a-n/lovelace-wallpanel#303]
I've just added this add on and it's strange that when I load the dashboard, it just goes back and forth between two images, but if I tab away, then back, it loads more images, but eventually just goes back and forth between two again.

Here is my yaml
```yaml
wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: false
  idle_time: 1
  image_url: media-source://media_source/local/TrueNAS/Photos/Publish To Nixplay/Home
  image_list_update_interval: 60
  image_order: random
  display_time: 6
  crossfade_time: 1
  cards: []
  debug: true
```
