### ISSUE TITLE
hide_toolbar only works on initial view

### ISSUE THREAD

**Issue by mrMetalWood** [j-a-n/lovelace-wallpanel#307]
First, thanks for this project! I love it. So many cool things are possible with this. 

I have the wallpanel setup with this config:

```
wallpanel:
  enabled: false
  profiles:
    device_448dfc81_110ce2c6:
      enabled: true
  profile: device_${browser_id}
  hide_sidebar: true
  hide_toolbar: true
  fullscreen: true
```

The wallpanel is only enabled for my tablet. As recommended I use the `browser_mod` for that. 

It all works fine when the dashboard gets loaded initially in Fully Kiosk Browser. The sidebar and the toolbar are hidden on the tablet.

When I then navigate to a subview on the dashboard, the top toolbar appears (which is necessary and good I guess because otherwise you wouldn't be able to go back). But when I then navigate back to the main view (with the arrow in the top left corner) the top toolbar stays activated and visible. Is this expected behaviour? I would expect that the toolbar would then be hidden again. Not sure if this is fixable or that once any navigation started the toolbar has to be visible for some reason.

The only way to get it working again for me is to refresh the browser or restart FKB.
