### ISSUE TITLE
Wallpanel dashboard makes HA companion app not register any screen press

### ISSUE THREAD

**Issue by DonLuigi** [j-a-n/lovelace-wallpanel#312]
I have been running lovelace yaml dashboard for years using 
```
wallpanel:
  enabled: true
  hide_sidebar: true
  hide_toolbar_action_icons: true
  idle_time: 0
...

```
and not really bothered updating companion app.

Now I got a new Xiaomi Redmi Pad SE 11" tablet, installed latest companion app, and whenever I open dashboard with above config, companion app doesn't register any screen press. The dashboard displays normally. In the end I have to kill companion app.

Tried it on my Samsung S24 phone as well - same thing.

As soon as I remove wallpanel section from yaml, the HA companion app works normally with that dashboard.

Anyone had that issue?
