### ISSUE TITLE
Set font size for screensaver card

### ISSUE THREAD

**Issue by briodan** [j-a-n/lovelace-wallpanel#317]
I'm trying to set the font size on a card in screensaver mode however it does not work i'm using

```yaml
wp_style:
  font-size: 3em
```

below is the full config of the dashboard

```yaml
wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  card_interaction: false
  style:
    wallpanel-screensaver-info-box:
      '--wp-card-width': 500px
    wallpanel-screensaver-info-box-content:
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-border-width': 0px
      '--primary-text-color': '#ffffff'
      '--secondary-text-color': '#dddddd'
      filter: >-
        drop-shadow(0px 0px 3px rgb(17, 17, 17)) drop-shadow(0px 0px 8px rgb(30,
        30, 30))
      width: calc(100vw - 50px)
      height: calc(100vh - 50px)
      justify-content: space-between
  cards:
    - type: custom:mushroom-chips-card
      chips:
        - type: template
          entity: lock.front_lock
          icon: |-
            {% if is_state("lock.front_lock", "locked") %}
            mdi:lock
            {% else %}
            mdi:lock-alert
            {% endif %}
          icon_color: |-
            {% if is_state("lock.front_lock", "locked") %}
            green
            {% else %}
            red
            {% endif %}
          content: Front Lock
      wp_style:
        grid-column: 1 / 1
        grid-row: 1 / 2
        align-self: start
    - type: custom:simple-clock-card
      use_military: true
      hide_seconds: false
      bold_clock: false
      font_size: 6rem
      paddingLeft_size: 32px
      paddingRight_size: 32px
      paddingTop_size: 20px
      paddingBottom_size: 20px
      wp_style:
        grid-row: 1 / 1
        grid-column: 2 / 2
        align-self: start
    - type: custom:mushroom-entity-card
      entity: input_text.word_of_the_day_french
      layout: vertical
      icon: mdi:account
      primary_info: state
      secondary_info: name
      icon_type: none
      tap_action:
        action: perform-action
        perform_action: script.set_word_of_the_day
        target: {}
      wp_style:
        grid-row: 2 / 2
        grid-column: 2 / 2
        align-self: start
        font-size: 4em
    - type: weather-forecast
      entity: weather.forecast
      show_forecast: true
      forecast_type: hourly
      wp_style:
        grid-row: 1 / 1
        grid-column: 3 /3
        align-self: start
views:
  - title: Home
    type: sections
    sections:
      - type: grid
        cards:
          - type: custom:mushroom-chips-card
            chips:
              - type: template
                entity: lock.front_lock
                icon: |-
                  {% if is_state("lock.front_lock", "locked") %}
                  mdi:lock
                  {% else %}
                  mdi:lock-alert
                  {% endif %}
                icon_color: |-
                  {% if is_state("lock.front_lock", "locked") %}
                  green
                  {% else %}
                  red
                  {% endif %}
                content: Front Lock
      - type: grid
        cards:
          - type: horizontal-stack
            cards:
              - type: custom:mushroom-template-card
                primary: Thermostat
                secondary: ''
                icon: mdi:thermometer
                tap_action:
                  action: navigate
                  navigation_path: /system-cards/thermostat
                icon_color: |-
                  {% if is_state("input_select.thermostat_state", "heat") %}
                  amber
                  {% elif is_state("input_select.thermostat_state", "cool") %}
                  blue
                  {% elif is_state("input_select.thermostat_state", "idle") %}
                  grey
                  {% endif %}
                multiline_secondary: false
                fill_container: true
                badge_icon: ''
                layout: vertical
          - type: horizontal-stack
            cards:
              - type: custom:mushroom-template-card
                primary: Garden
                secondary: ''
                icon: mdi:flower
                tap_action:
                  action: navigate
                  navigation_path: /system-cards/garden
                icon_color: green
                layout: vertical
                fill_container: false
    badges: []
    max_columns: 3
    cards: []
```
