### ISSUE TITLE
With basic configuration- where is the weather defined?

### ISSUE THREAD

**Issue by SteveRMann** [j-a-n/lovelace-wallpanel#323]
**Never mind**. Stumbled around and found the answer.
It would have helped if the default for cards: were in the summary table.

Here is my configuration:
```
wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  camera_motion_detection_enabled: true
  keep_screen_on_time: 1800

```
It looks pretty good so far. Here is what I see:
![wallpaper](https://github.com/user-attachments/assets/e9e6fe42-4262-4528-bd29-40f468193f27)

In the top-left of the WallPanel is an area for my local weather.  But, where is this entity defined?
