### ISSUE TITLE
Strategy iframe load error

### ISSUE THREAD

**Issue by jotadesigns** [j-a-n/lovelace-wallpanel#324]
When you try to use wallpanel in an iframe strategy, it only works when you reload/save the yaml.

```
strategy:
  type: iframe
  url: https://xxxxxxx.com/
wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
```

Am I doing something wrong?
