### ISSUE TITLE
Toolbar is always visible with 4.35.*

### ISSUE THREAD

**Issue by richardmx5guys** [j-a-n/lovelace-wallpanel#347]
Once updated to 4.35.* the toolbar remains visible whilst hide_toolbar: true.
The app reloads the screen every so often.

All was great with 4.34.*

**Comment by j-a-n** [comment]
Possibly related to #343
Please try if version 4.35.3 fixes the issue.

**Comment by richardmx5guys** [comment]
It works now but it takes a while for the tool_bar to disappear. I will be watching it today.

**Comment by ProximusAl** [comment]
Agreed, there is a small delay of the toolbars now hiding.  I have my dashboard to auto refresh every 5 minutes, and the toolbar pops up, then disappears after about 3-4 seconds.

**Comment by j-a-n** [comment]
This should now be resolved with version 4.36.0.

**Comment by carslen** [comment]
I'm facing the same issue on my Fire HD 10 Tablet even with running the latest 4.35.3. I'm using the profiles config:

```yaml
wallpanel:
  enabled: false
  hide_toolbar: false
  hide_sidebar: true
[ ... ]
  profiles:
    user.userName:
      enabled: true
      hide_toolbar_action_icons: true
```

As it has been asked in linked issue, the used WebView Version is 128.amazon-webview-v128-6613.6613.187.32. Fire OS 8.3.3.2.
