### ISSUE TITLE
Add support for show_image_info to image entities

### ISSUE THREAD

**Issue by syphernl** [j-a-n/lovelace-wallpanel#349]
Would it be possible to read the EXIF data from `image.` entities in HomeAssistant, so `show_image_info` can be used with those as well?

Example attributes on one of my `image` entities (created by [immich-home-assistant](https://github.com/outadoc/immich-home-assistant))

```yaml
media_exif:
  make: OnePlus
  model: ONEPLUS A6013
  exifImageWidth: 3456
  exifImageHeight: 4608
  fileSizeInByte: 1593786
  orientation: "1"
  dateTimeOriginal: "2020-05-11T07:30:52.399+00:00"
  modifyDate: "2020-05-11T07:30:52.399+00:00"
  timeZone: Europe/Brussels
  lensModel: null
  fNumber: 2
  focalLength: 3.48
  iso: 200
  exposureTime: 1/100
  latitude: REDACTED
  longitude: REDACTED
  city: REDACTED
  state: REDACTED
  country: REDACTED
  description: ""
  projectionType: null
  rating: null
```
