### ISSUE TITLE
image background not updating instantly anymore

### ISSUE THREAD

**Issue by IoSonoAndreaZ** [j-a-n/lovelace-wallpanel#352]
Hi, I have an image template that shows a black image usually but then becomes the cover of the movie or series or music I'm playing with plex, if something is playing:

```

template:
  - image:
      - name: Copertina Plex Krogpc Dinamica
        url: "{% if is_state('media_player.plex_plex_htpc_for_linux_krogpc_skylake', 'playing') or is_state('media_player.plex_plex_htpc_for_linux_krogpc_skylake', 'paused') %}https://192.168.178.56:8123{{ state_attr('media_player.plex_plex_htpc_for_linux_krogpc_skylake', 'entity_picture') }}{% elif is_state('media_player.plex_plexamp_krogpc_skylake', 'playing') %}https://192.168.178.56:8123{{ state_attr('media_player.plex_plexamp_krogpc_skylake', 'entity_picture') }}{% else %}https://192.168.178.56:8123/api/image/serve/471596301c211efc1bbdf43eb99ad2fc/original{% endif %}"
        verify_ssl: false
        unique_id: copertina_plex_krogpc_dinamica
```

This is used as background for wallpanel.

My wallpanel code:

```
wallpanel:
  enabled: false
  enabled_on_tabs:
    - ThinkPadView
  debug: false
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: false
  idle_time: 30
  keep_screen_on_time: 0
  black_screen_after_time: 0
  control_reactivation_time: 1
  screensaver_stop_navigation_path: /op5t-satellite/ThinkPadView
  display_time: 5
  image_url: media-entity://image.copertina_plex_krogpc_dinamica
  image_fit: contain
  image_list_update_interval: 3600
  image_background: image.copertina_plex_krogpc_dinamica
  image_order: sorted
  image_excludes: []
  show_exif_info: false
  fetch_address_data: true
  exif_info_template: >-
    ${address.town|address.city!prefix=!suffix= //
    }${DateTimeOriginal!options=year:numeric,month:long}
  screensaver_entity: input_boolean.lenovoscreensaver
  info_animation_duration_x: 30
  info_animation_duration_y: 11
  info_animation_timing_function_x: ease-in-out
  info_animation_timing_function_y: ease-in-out
  info_move_pattern: corners
  info_move_interval: 0
  info_move_fade_duration: 2
  stop_screensaver_on_mouse_move: false
  style:
    wallpanel-screensaver-info-box:
      '--wp-card-width': 450px
      background-color: '#00000099'
      box-shadow: >-
        0px 2px 1px -1px rgba(0, 0, 0, 0.2), 0px 1px 1px 0px rgba(0, 0, 0,
        0.14), 0px 1px 3px 0px rgba(0, 0, 0, 0.12)
    wallpanel-screensaver-info-box-content:
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-border-width': 3px
      '--primary-background-color': '#111111'
      '--secondary-background-color': '#202020'
      '--primary-text-color': '#e1e1e1'
      '--secondary-text-color': '#9b9b9b'
  cards:
    - type: vertical-stack
      cards:
        - type: custom:clock-weather-card
          entity: weather.openweathermap
          sun_entity: sun.sun
          temperature_sensor: sensor.shelly_h_t_nero_temperature
          humidity_sensor: sensor.shelly_h_t_bianco_humidity
          show_humidity: false
          weather_icon_type: fill
          forecast_rows: 3
          locale: it
          time_pattern: HH:mm
          time_format: 24
          date_pattern: cccc d MMM yyyy
          hide_today_section: false
          hide_forecast_section: true
          hide_clock: false
          hide_date: false
          show_decimal: true
          card_mod:
            style: |
              ha-card {
                zoom: 200%;
                font-size: 20px;
                width: 400px !important;
                #height: 400px !important;
                margin-left: -67%;
                #margin-top: 60%;
                background-color: transparent;
                text-shadow: 1px 1px 3px black;
                border: transparent;
              }

```

Until couple days ago the background updated itself instantly reflecting the template result, but now it refreshes after long time and it's not updated as before.

Maybe some caching is introduced in the latest updates? How to revert wallpanel to previous behavior?
