### ISSUE TITLE
Wallpanel seems to cut off button-card size

### ISSUE THREAD

**Issue by Dutcherik** [j-a-n/lovelace-wallpanel#355]
[YAML1.txt](https://github.com/user-attachments/files/18641135/YAML1.txt)
[YAML2.txt](https://github.com/user-attachments/files/18641136/YAML2.txt)

I have a dashboard based on a custom:button-card. I used that dashboard with wallpanel to show on a small screen. About a month ago it stopped working properly.
The size of button-card seems to be cut off on the right side.

When I run the yaml file without the wallpanel section the size of the button-card is OK (755px).
First yaml: without Wallpanel section
Second yaml: with Wallpanel section

**Comment by j-a-n** [comment]
Hi,

try adding the following to the wallpanel config:
```yaml
wallpanel:
  style:
    wallpanel-screensaver-info-box:
      '--wp-card-margin': 0px
```

**Comment by Dutcherik** [comment]
[YAML3.txt](https://github.com/user-attachments/files/18669628/YAML3.txt)

Unfortunately that does not help.

**Comment by j-a-n** [comment]
There is a typo in your config:
`wallpaper-screensaver-info-box` needs to be `wallpanel-screensaver-info-box`.

**Comment by Dutcherik** [comment]
Thx. That was helpful. Now the card is complete (rounded edges on both sides), but is not the defined size (755x445). Without the wallpanel section it is.

**Comment by j-a-n** [comment]
Please try this:
```yaml
wallpanel:
  style:
    wallpanel-screensaver-info-box:
      '--wp-card-width': fit-content
```
