### ISSUE TITLE
Camera detection won't start

### ISSUE THREAD

**Issue by cmeissner** [j-a-n/lovelace-wallpanel#356]
I have a dashboard configured where I want to use camera detection. My configuration looks as followed:

```yaml
wallpanel:
  enabled: false
  hide_toolbar: fase
  hide_toolbar_action_icons: true
  hide_sidebar: true
  fullscreen: true
  keep_screen_on_time: 86400
  black_screen_after_time: 900
  screensaver_stop_navigation_path: /dashboard-home/info
  profiles:
    user.kiosk:
      enabled: true
      camera_motion_detection_enabled: true
      camera_motion_detection_capture_visible: true
```

The screensaver starts as expected, but the camera won't start. 

I tested the configuration on different devices with different browsers. 

- laptop (chrome, firefox)
- smartphone (chrome, fully-kiosk browser, home assistant companion app)
- tablet (chrome, fully-kiosk browser, home assistant companion app)

With no combination, the camera won't start and only tapping on the screen will be the last resort for waking the device.
