### ISSUE TITLE
hidden sidebar and action menu revealed on Android after looking at history

### ISSUE THREAD

**Issue by DonLuigi** [j-a-n/lovelace-wallpanel#361]
I have a simple test dashboard:
```
wallpanel:
  hide_sidebar: true
  hide_toolbar_action_icons: true
views:
  - title: Home
    type: masonry
    cards:
      - type: entities
        entities:
          - entity: sensor.sun_next_dawn

```
Initially sidebar and action menu are hidden on Android Companion app.
After I press on "Sun next dawn", and then on "Show more" and select a timeframe, after coming back to dashboard, sidebar and action menu are revealed.

Version: 4.39.0
Android app: latest version
PC: Works on PC
