### ISSUE TITLE
Mismatch between image and EXIF information

### ISSUE THREAD

**Issue by syphernl** [j-a-n/lovelace-wallpanel#368]
The EXIF data frequently shows information for the next image, not the current one.

Relevant config:

```yaml
wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  idle_time: 30
  display_time: 120
  image_url: media-entity://image.immich_family_and_friends
  show_image_info: true
  fetch_address_data: false # no need as we already have the city/country in the image info
  image_info_template: >-
    <ha-icon icon="mdi:map-marker"></ha-icon>${city|country}<br>
    <ha-icon icon="mdi:calendar"></ha-icon>
    ${dateTimeOriginal!options=day:2-digit}
    ${dateTimeOriginal!options=month:long}
    ${dateTimeOriginal!options=year:numeric}
```
