### ISSUE TITLE
hide_toolbar_action_icons not working in subviews where hide_toolbar is active (not active in subviews only)

### ISSUE THREAD

**Issue by rafareusch** [j-a-n/lovelace-wallpanel#372]
Heres a scenario to reproduce it  via NABUCASA (didn't tested local yet)

- A: If I go from Dashboard 1 to Dashboard 2, the `hide_toolbar_action_icons `is applied correctly.
- B: If i go from Dashboard 1 to Subview in the **SAME Dashboard**, the `hide_toolbar_action_icons ` is not applied

If I set in Dashboard 1, `hide_toolbar: false`, the scenario B works fine

DASHBOARD 1:
```
wallpanel:
  enabled: true
  hide_toolbar: true
  idle_time: 0
  hide_toolbar_on_subviews: false
  hide_toolbar_action_icons: true
views:
  - type: masonry
    title: home
    path: home
    cards:
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: navigate
          navigation_path: /dashboard-wallpaneltest2/0
        name: GO TO SUBVIEW DIFFERENT DASHBOARD
      - show_name: true
        show_icon: true
        type: button
        tap_action:
          action: navigate
          navigation_path: /dashboard-wallpaneltest/ssss
        name: GO TO SUBVIEW SAME DASHBOARD
  - type: sections
    max_columns: 4
    subview: true
    path: ssss
    sections:
      - type: grid
        cards:
          - type: heading
            heading: New section

```

DASHBOARD 2:
```
wallpanel:
  enabled: true
  hide_toolbar: false
  hide_toolbar_action_icons: true
  idle_time: 0
views:
  - title: SUBVIEW TEST
    type: sections
    max_columns: 4
    subview: true
    sections:
      - type: grid
        cards:
          - type: heading
            heading: New section
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            name: LIGHT SUBVIEW
            icon: mdi:alarm-light

```

Browser Console LOG
(Started on dashboard 1 and entered subview of dashboard 1)

```
Wallpanel config is now: {enabled: true, enabled_on_tabs: Array(0), debug: false, wait_for_browser_mod_time: 0.25, log_level_console: 'debug', …}
wallpanel.js?hacstag=8795064164409:210 Update hass
wallpanel.js?hacstag=8795064164409:210 Preloading images
wallpanel.js?hacstag=8795064164409:210 Updating image 'wallpanel-screensaver-image-one' from 'https://picsum.photos/479/607?random=1740345315'
wallpanel.js?hacstag=8795064164409:210 Location changed from 'null' to 'NABUCASA_URL_HIDDEN/dashboard-wallpaneltest/home'
wallpanel.js?hacstag=8795064164409:210 Wallpanel config is now: {enabled: true, enabled_on_tabs: Array(0), debug: false, wait_for_browser_mod_time: 0.25, log_level_console: 'debug', …}
wallpanel.js?hacstag=8795064164409:210 activateWallpanel
wallpanel.js?hacstag=8795064164409:210 setToolbarVisibility: hideToolbar=true, hideActionItems=true
wallpanel.js?hacstag=8795064164409:210 setSidebarVisibility: hidden=false
log-message.ts:36 
            
(anonymous) @ stacktrace-gps.js:218
_get @ stacktrace-gps.js:195
(anonymous) @ stacktrace-gps.js:289
findFunctionName @ stacktrace-gps.js:287
(anonymous) @ stacktrace-gps.js:272
Promise.then
(anonymous) @ stacktrace-gps.js:267
pinpoint @ stacktrace-gps.js:266
(anonymous) @ stacktrace.js:113
(anonymous) @ stacktrace.js:108
(anonymous) @ stacktrace.js:107
fromError @ stacktrace.js:105
t @ log-message.ts:36
(anonymous) @ logging-mixin.ts:48Understand this errorAI
5wallpanel.js?hacstag=8795064164409:210 Update hass
wallpanel.js?hacstag=8795064164409:210 Updating image 'wallpanel-screensaver-image-two' from 'https://picsum.photos/479/607?random=1740345317'
wallpanel.js?hacstag=8795064164409:210 Setup screensaver
wallpanel.js?hacstag=8795064164409:210 navigate NABUCASA_URL_HIDDEN/dashboard-wallpaneltest/ssss NavigateEvent {isTrusted: true, navigationType: 'push', destination: NavigationDestination, canTransition: true, canIntercept: true, …}
wallpanel.js?hacstag=8795064164409:210 location-changed NABUCASA_URL_HIDDEN/dashboard-wallpaneltest/ssss Event {isTrusted: false, detail: {…}, type: 'location-changed', target: Window, currentTarget: Window, …}
wallpanel.js?hacstag=8795064164409:210 Update hass
wallpanel.js?hacstag=8795064164409:210 Location changed from 'NABUCASA_URL_HIDDEN/dashboard-wallpaneltest/home' to 'NABUCASA_URL_HIDDEN/dashboard-wallpaneltest/ssss'
wallpanel.js?hacstag=8795064164409:210 Wallpanel config is now: {enabled: true, enabled_on_tabs: Array(0), debug: false, wait_for_browser_mod_time: 0.25, log_level_console: 'debug', …}
wallpanel.js?hacstag=8795064164409:210 activateWallpanel
wallpanel.js?hacstag=8795064164409:210 setToolbarVisibility: hideToolbar=false, hideActionItems=false
wallpanel.js?hacstag=8795064164409:210 setSidebarVisibility: hidden=false
wallpanel.js?hacstag=8795064164409:210 Location changed from 'NABUCASA_URL_HIDDEN/dashboard-wallpaneltest/ssss' to 'NABUCASA_URL_HIDDEN/dashboard-wallpaneltest/ssss'
9wallpanel.js?hacstag=8795064164409:210 Update hass
```
