### ISSUE TITLE
hide_toolbar and hide_sidebar are not working

### ISSUE THREAD

**Issue by warning939** [j-a-n/lovelace-wallpanel#375]
Hi Jan,

Thank you for your project!
The toolbar and the sidebar appear even if I have this in the config:

```
wallpanel:
  enabled: true
  hide_toolbar: true
views:
  - title: SUBVIEW TEST
    type: sections
    max_columns: 4
    subview: true
    sections:
      - type: grid
        cards:
          - type: heading
            heading: New section
          - show_name: true
            show_icon: true
            type: button
            tap_action:
              action: toggle
            name: LIGHT SUBVIEW
            icon: mdi:alarm-light
    cards: []
```

I created a brand new HA in Docker (Synology), there is no other plug-in or JS.

**Comment by warning939** [comment]
This is the error on fronend:

![Image](https://github.com/user-attachments/assets/5f1da0df-6964-4956-86c0-fdc101e86ead)

**Comment by curtisdr** [comment]
Not sure if this is related, but as of a couple of days ago on my Amazon Fire HD 10, the default Lovelace for that device doesn't load with the following code.  You can see the toolbar but nothing else.  Happens in Fully Kiosk and the HA Companion app.
```
wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: false
  idle_time: 0
  fullscreen: true
```
If I change hide_sidebar to 'true', the page now loads but still shows the toolbar.
