### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by cwitting** [j-a-n/lovelace-wallpanel#38]
Hi I cannot get this to work.

I tried adding a simple dashboard with this, but nothing shows after the timeout.
Here is my dashboard configuration.

```
wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  idle_time: 10
title: Wall Test
views:
  - title: Home
    cards:
      - type: weather-forecast
        entity: weather.hjem
```

Do I do something wrong?
