### ISSUE TITLE
Black screen between images

### ISSUE THREAD

**Issue by NoisyBoy1308** [j-a-n/lovelace-wallpanel#394]
When the slideshow changes images, the old image fades out, then before the new image starts to fade in, a black screen is displayed with exact the same duration as  defined in display_time. 
I want to use my wallpanel as a digital frame when it is not used. So i want to set long display times, but  the screen goes black half the time. 
is there any known way to configure this?

**Comment by j-a-n** [comment]
It seems that some images cannot be loaded. Are there errors in the browser console (F12)?

**Comment by sirnightowl** [comment]
So it seems to only be happening on my Raspberry Pi 4 setup, When the screensaver happens on my main PC it works fine with no gaps yet on the Pi it has a 10-15 second black scene inbetween the images. F12 doesnt work on the Pi kiosk environment I have setup. 
Setup with the issue:
> Raspberry Pi 4
> Installed kiosk mode following 
https://greysonlopez.com/2024/12/30/building-a-custom-dashboard-with-home-assistant-and-a-raspberry-pi/
> Installed https://j-a-n.github.io/lovelace-wallpanel/
> This is my wallpanel code inserted top of the dashboard yaml

```
wallpanel:
  enabled: true
  hide_toolbar: false
  keep_toolbar_space: true
  hide_sidebar: true
  fullscreen: false
  idle_time: 15
  cards: []
  screensaver_entity: input_boolean.wallpanel_screensaver
  image_url: /local/screensaver
  image_order: sorted
  image_list_update_interval: 3600
  display_time: 30
  black_screen_after_time: 7200
  control_reactivation_time: 1
  crossfade_time: 10
  fade_in_time: 10
  fade_out_time_screensaver_entity: 10
  show_progress_bar: true
```

Hope that's helpful - let me know if you need me to check anything and I'll take a look as soon as I can :)
