### ISSUE TITLE
Pull EXIF data from immich - Enhancement

### ISSUE THREAD

**Issue by bigthrilla** [j-a-n/lovelace-wallpanel#396]
Poured over the config doc and found **_show_image_info_** - but only works for local and unsplash according to the documentation (I tried anyway, no luck).  Looked through the code and I thought I saw an area where it uses EXIF data from immich images so I'm hoping there's a way this could be implemented.

End result is I would like to have the date a photo was taken displayed, similarly to how the google home products do in their images.  Thank you for your consideration, this is an impressive project 👍

**Comment by j-a-n** [comment]
Hello,

this already possible, you can access every exif attribute.
For example:

```yaml
wallpanel:
  show_image_info: true
  image_info_template: >-
    <span style="color:#990000">//${dateTimeOriginal!options=year:numeric,month:long}</span>
```
