### ISSUE TITLE
View Navigate fails if same View selected as prior to Wallpanel activation

### ISSUE THREAD

**Issue by kabongsteve** [j-a-n/lovelace-wallpanel#405]
I have a Wallpanel (Sonoff NSPro 120) that shows a dashboard with 7 views.  

The last View is a grid of button cards, with each button's tap_action: navigating to one of the other views.

I display this View using wallpanel, when the screen saver starts, so when the panel is activated (presense sensor) the buttons are shown to quickly jump to the wanted View.

Unfortunately, this doesn't work if the requested view is the one that was being displayed prior to the wallpanel activating.

EG sequence
Display currently showing View "0" Lights
Wallpanel activates
"Views" view is displayed with its 6 buttons
Display dims
Display is awoken by activation (presense)
"Lights" button is pressed                                         --- nothing happens, as if button press didn't work
"Shutters" button is pressed                                      --- wall panel disappears and "shutters" view displayed

next time around, "Shutters" button does nothing, but "Lights" button works as expected.

```
wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: false
  idle_time: 15
  show_images: false
  card_interaction: true
  cards: []
  views:
    - title: Views
views:
   ...
 - type: panel
    path: ''
    title: Views
    cards:
      - square: true
        type: grid
        cards:
          - show_name: true
            show_icon: true
            type: button
            icon: mdi:ceiling-light-multiple-outline
            tap_action:
              action: navigate
              navigation_path: /dashboard-loungewall/0
            show_state: false
          - show_name: true
            show_icon: true
            type: button
            icon: mdi:air-conditioner
            tap_action:
              action: navigate
              navigation_path: /dashboard-loungewall/1

```

**Comment by j-a-n** [comment]
I think this occurs because no navigation event is triggered when the navigation path remains unchanged.
To navigate to a different view when the screensaver starts, you can use `screensaver_stop_navigation_path` (which should be named `screensaver_start_navigation_path`). For example:

```yaml
wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: false
  idle_time: 15
  show_images: false
  card_interaction: true
  cards: []
  views:
    - title: Views
  screensaver_stop_navigation_path: /dashboard-loungewall/2
```
