### ISSUE TITLE
Screensaver and Blanking not working, what am I doing wrong?  Thx for the help!

### ISSUE THREAD

**Issue by Ltek** [j-a-n/lovelace-wallpanel#407]
New to wallpanel, its working fine (thanks again for this awesome app!) but I cant get the Screensaver to run, ever... nor does it the screen blank. Please lmk what I'm missing, thank you.

```
wallpanel:
  enabled: true
  enabled_on_tabs:
    - wallpanel
  debug: false
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  idle_time: 10
  fade_in_time: 3
  crossfade_time: 2
  display_time: 20
  black_screen_after_time: 90
  control_reactivation_time: 0.5
  keep_screen_on_time: 0
  screensaver_stop_navigation_path: /dashboard-wallpanel
  image_url: media-source://synology_dsm/1980QXRRECDJ1/26Hfq7ydY
  image_fit: cover
  image_animation_ken_burns: true
  image_list_update_interval: 3600
  image_order: sorted
  image_excludes: []
  show_exif_info: false
  fetch_address_data: true
  exif_info_template: >-
    ${address.town|address.city!prefix=!suffix= //
    }${DateTimeOriginal!options=year:numeric,month:long}
  screensaver_entity: input_boolean.kitchentabletscreensaver
  info_animation_duration_x: 30
  info_animation_duration_y: 11
  info_animation_timing_function_x: ease-in-out
  info_animation_timing_function_y: ease-in-out
  info_move_pattern: random
  info_move_interval: 0
  info_move_fade_duration: 2
  cards:
    - type: vertical-stack
      cards:
        - type: weather-forecast
          entity: weather.forecast_home
          show_current: true
          show_forecast: true
          forecast_type: daily
          forecast_slots: 5
          secondary_info_attribute: humidity
```

**Comment by j-a-n** [comment]
Please start with a simple configuration and check if the screensaver is starting. If yes, add more configuration options step by step.
You can start with:
```yaml
wallpanel:
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  idle_time: 10
  display_time: 20
  black_screen_after_time: 90
  image_url: media-source://synology_dsm/1980QXRRECDJ1/26Hfq7ydY
  cards:
    - type: vertical-stack
      cards:
        - type: weather-forecast
          entity: weather.forecast_home
          show_current: true
          show_forecast: true
          forecast_type: daily
          forecast_slots: 5
          secondary_info_attribute: humidity
```
