### ISSUE TITLE
Unable to edit dashboard

### ISSUE THREAD

**Issue by WarrenSchultz** [j-a-n/lovelace-wallpanel#41]
So, I tried the short example YML config, and managed to lock myself out of my test dashboard I'd created. :)

No huge loss, but I'm curious how to get to the editor after using these settings
```
wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true

```

**Comment by beerygaz** [comment]
I had the same challenge, but you can get back in by adding ?wp_enabled=false to the end of your dashboard url

`https://homeassistant8123/lovelace/irrigation?wp_enabled=false&edit=1`

**Comment by navarro152** [comment]
@WarrenSchultz  Where are you adding this? I haven't been able to arrive to even lock myself out. I have this on my edit configuration. Not sure really well, how to start, due to ha does not let me start with a blank page
![Screen Shot 2022-09-23 at 5 39 42 PM](https://user-images.githubusercontent.com/70385826/192060337-1b972991-2dad-4875-95fe-2006dc4c9709.png)

**Comment by j-a-n** [comment]
You can add the wallpanel configuration to an existing dashboard.
You can add a new dashboard in Settings -> Dashboards.

**Comment by navarro152** [comment]
@j-a-n  thank you so much for replying and mostly for doing this amazing work. I have the feeling that this wallpanel will be the missing part for my house. Now that I have your attention, it my first time going to edit on deep a dashboard from the RAW configuration. And I am a bit lost how to start. Is this the correct start or I need to do something different. I am adding the wallpanel configuration as a new dashboard view

`views:
  - title: Wallpanel
    wallpanel:
      enabled: true
      hide_toolbar: true
      hide_sidebar: true
      fullscreen: true
      black_screen_after_time: 10
`
I am going ok or I need to do something different

![Screen Shot 2022-09-24 at 2 36 10 PM](https://user-images.githubusercontent.com/70385826/192113736-1ad0ff65-cf84-4861-8c13-96b6bdedbd92.png)

**Comment by WarrenSchultz** [comment]
@navarro152 Unless I'm doing something wrong, this is the layout you want, it goes outside the views:
```
wallpanel:
    enabled: true
    hide_toolbar: false
    hide_sidebar: true
    fullscreen: true
    idle_time: 5
views:
  - theme: Backend-selected
    title: Home Dashboard
etc
```
And the tip from beerygaz worked great. 
?wp_enabled=false&edit=1 allowed me to jump into edit mode. Thanks!
