### ISSUE TITLE
`image_background: color` no longer works

### ISSUE THREAD

**Issue by Telemaniaka** [j-a-n/lovelace-wallpanel#415]
Hi,

I noticed today that the screensaver now always shows a cropped and blurred background behind the image displayed.
Explicitly setting `image_background: color` doesn't seem to work either. 

I think that logic got removed by accident in the refactor here:  https://github.com/j-a-n/lovelace-wallpanel/commit/58b94d48019c1c2d14f81788c5106d9c399206f2 

Found a temporary workaround by adding: 
```
style:
    wallpanel-screensaver-image-background:
        background: '#00000000'
        background-image: 'unset !important'
```
