### ISSUE TITLE
DSM photos as screensaver

### ISSUE THREAD

**Issue by jurr13n** [j-a-n/lovelace-wallpanel#416]
hello, 

im trying to use my DSM photo album for screen saver but i cant get it to work

wallpanel:
  enabled: true
  idle_time: 10
  image_url: /synology_dsm/2190TERAXZ198/6_EkQtLoE7x

so i copied the patch from the url in media then u used the decoder then got this but it jsut doesnt seem to work

**Comment by j-a-n** [comment]
Hello,

please try:
```yaml
wallpanel:
  enabled: true
  idle_time: 10
  image_url: media-source://synology_dsm/2190TERAXZ198/6_EkQtLoE7x
  exclude_filenames:
    - '/@eaDir'
```
