### ISSUE TITLE
Left margin appearing when using wiews

### ISSUE THREAD

**Issue by BenDavidson90** [j-a-n/lovelace-wallpanel#423]
Hi,

When I use the parameter `views`, a left margin is appearing.

Here is a screenshot without `views` included (the badges are on the WallPanel config):
![Image](https://github.com/user-attachments/assets/e489de26-a9bf-4825-9f90-e50291c51a42)

Here is a screenshot with `views` included (the test badge is on the view itself):
![Image](https://github.com/user-attachments/assets/19d247b0-9585-4c50-b034-71cccb6479a1)

Here is the code:
```yaml
wallpanel:
  enabled: true
  debug: false
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: false
  idle_time: 1
  image_url: media-entity://image.immich_favorites
  image_fit_landscape: cover
  cards: []
  views:
    - title: Wallpanel
  style:
    wallpanel-screensaver-info-box-views:
      width: 100vw
```

I tried some `margin-left` and `padding-left` minus something but nothing change.

**Comment by j-a-n** [comment]
You can use:
```yaml
 style:
    wallpanel-screensaver-info-container:
      padding: 0px
```
