### ISSUE TITLE
Some images being stretched since latest update

### ISSUE THREAD

**Issue by ShaneK** [j-a-n/lovelace-wallpanel#428]
Since the most recent update, some images are being stretched when displayed. I don't know the pattern for these images, it's supposed to show the stretched image blurred in the background and the normal version in front and that happens a lot of the time, but some images seem to not be behaving as expected.

I have the following relevant settings:
```yaml
[...]
  image_background: image
  image_fit_portrait: contain
  image_fit_landscape: contain
[...]
```

It looks like the ones being stretched are portrait images, but maybe they're wider than the portrait images not being stretched because of a higher resolution? I don't know. I'd really like if they could go back to behaving like the other portrait images though.

**Comment by ShaneK** [comment]
Sorry, I'd like to show example images, but they're pictures of my kids and I don't really post them on the internet. Here's some dimensions:

Portrait images I know are stretched:

![Image](https://github.com/user-attachments/assets/658bae4c-f2b5-415a-904a-4bc41e9481a5)

![Image](https://github.com/user-attachments/assets/c691c4d5-6980-468d-9658-05a2cacf8dd9)

Portrait images that are not stretched and behaves as expected:

![Image](https://github.com/user-attachments/assets/b6ffc3ee-0781-4efb-88cb-eea23cc63cf8)

![Image](https://github.com/user-attachments/assets/8dc75d92-a076-40dd-a08e-17d11c05694f)

I'm also yet unable to verify if these same images will become stretched/act normally at different times.

Let me know if you need more information!

**Comment by j-a-n** [comment]
Thanks for reporting!
It would be easier to fix if I could reproduce the issue.
So, if you find some image you can share with me, you can send it to oss@janschneider.net
Perhaps you can edit one of these pictures?

**Comment by ShaneK** [comment]
Sent an email, thank you!

**Comment by nirnachmani** [comment]
I am having the same issue. It is happening with some of my photos. I am getting my photos via Immich API in case this is the issue. I have to go to work so I can't really look for the pattern of which photos are affected.

**Comment by ShaneK** [comment]
Mine are also coming from Immich fwiw 

Also, I noted this in an email, but it's happening to videos too

**Comment by svewag** [comment]
I experience the same issue

**Comment by sergon2000** [comment]
Same issue.
You guys can temporarily downgrade the integration to v4.46.0 in order to fix that.

**Comment by j-a-n** [comment]
Could you please test if version 4.47.1 fixes the issue?

**Comment by sergon2000** [comment]
- version 4.46.0: no issues at all.
- version 4.47.0: I'm experiencing both issues: this one and also [this](https://github.com/j-a-n/lovelace-wallpanel/issues/419). But both issues seem to be related with each other because they show up all together only in certain photos.
- version 4.47.1: the stretch issue seems to be gone but I still don't see exif information.

**Comment by ShaneK** [comment]
Very close! For some reason, on images this was impacting, it's not centering them horizontally anymore

![image](https://github.com/user-attachments/assets/1a723393-6692-4d1c-b7ec-f3fa5d2824cb)

![image](https://github.com/user-attachments/assets/041fb4e6-ae4e-4980-bd19-edf950aa5c18)

The second image isn't what I expect either, I expect it to be full height or full width or both, but that one is neither

**Comment by meks007** [comment]
same issues with 4.47.1 as @ShaneK has.

**Comment by nirnachmani** [comment]
For me the issue changed a bit from 4.47.0 to 4.47.1. In 4.47.0 some photos were presented using the wrong ratio, making them look stretched. In 4.47.1 the image is presented in the center of the screen, in the correct ratio but not in full screen. I attached two examples with the issue in 4.47.1. One image of each is the original which is displayed incorrectly and the other is how it is displayed. 

![Image](https://github.com/user-attachments/assets/2757ae36-6156-4543-b019-7a56a3549d53)
![Image](https://github.com/user-attachments/assets/23689366-b248-4c7e-890c-6141435d1e41)

![Image](https://github.com/user-attachments/assets/052ebb48-394f-4646-a310-8b48e251bf1b)
![Image](https://github.com/user-attachments/assets/a7988a0d-ce49-4b22-aa11-ff0493f5776c)

This is my relevant Wallpanel configuration (redacted):

```
  image_url: immich+https://xxxxxxx.com/api
  immich_api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
  immich_album_names:
    - Tablet
  image_animation_ken_burns: true
  image_animation_ken_burns_delay: 5
  image_animation_ken_burns_zoom: 1.3
```

**Comment by j-a-n** [comment]
Thanks for all the examples and information!
I'm pretty confident that the problem is now finally fixed in version 4.47.2.

**Comment by ShaneK** [comment]
Awesome! This looks like it's working much nicer now, thank you!

**Comment by meks007** [comment]
Can confirm it's working pretty well now.

**Comment by nirnachmani** [comment]
Looking good! Thank you.

**Comment by j-a-n** [comment]
Closing this, feel free to reopen if the issue persists.

**Comment by ghost** [comment]
Hey @j-a-n ,

I'm not sure if I'm understanding something wrong, because it's still not working for me. If an image in portrait format is displayed on a device in landscape format, this had the effect in version 4.46 that the background blurred. If I read the comments above, then some had the problem, which no longer exists with the latest version. But I still have the problem. Black bars are displayed on the side.

That is my config:

```
wallpanel:
  enabled: true
  image_url: media-source://media_source/local/bilderrahmen
  hide_sidebar: false
  hide_toolbar: false
  image_order: random
  image_fit_portrait: contain
  idle_time: 3
  fade_in_time: 2
  crossfade_time: 15
  display_time: 900
  cards: []
```

See this example:

![Image](https://github.com/user-attachments/assets/d4d8017d-d1fb-4fc3-849b-667727781dae)

In version 4.46, the black borders (marked in red) do not exist. At this point, the same image is blurred again in the background.
