### ISSUE TITLE
Grid Layout Help

### ISSUE THREAD

**Issue by janstadt** [j-a-n/lovelace-wallpanel#429]
I posted this here: https://community.home-assistant.io/t/achieving-a-custom-grid-layout-with-lovelace/760922/7?u=janstadt but basically im looking for a two column layout where 1 has a row that is 66% of the height and the other is 67%, and then another column that is 100% of the remainder of the screen. 

```
---------------------------
|           |             |
|           |             |
|           |             |
-------------             |
|           |             |
|           |             |
---------------------------
```

I've tried a few things, but i cant seem to get it right. I also tried just doing a single grid card and then used the additional fields to try and get the info card to display how i had hoped. 

What im trying to achieve is a weather card in the top left, a horizontal stack of button actions in the bottom left, and then a conditional card in the right column to show/hide depending on when i toggle a button in the horizontal stack.

@j-a-n any help would be greatly appreciated.

**Comment by janstadt** [comment]
Update, i found the docs about making the info box cover the whole screen. I think this will help out since i want it to be over the entire display but in that layout above. 

```
  style:
    wallpanel-screensaver-info-container:
      padding: 0px
    wallpanel-screensaver-info-box-views:
      width: 100vw
```

**Comment by j-a-n** [comment]
Here is a full dashboard YAML you can use as a starting point:
```yaml
wallpanel:
  enabled: true
  views:
    - title: Home
      wp_style:
        height: 100vh
        width: 100vw
  cards: []
  style:
    wallpanel-screensaver-info-container:
      padding: 0px
    wallpanel-screensaver-info-box-views:
      width: 100vw
      height: 100vh
views:
  - title: Home
    type: custom:grid-layout
    layout:
      height: 100%
      grid-template-columns: auto auto
      grid-template-rows: 67% 33%
      grid-template-areas: |
        "weather conditional"
        "buttons conditional"
    cards:
      - type: markdown
        content: Weather Area
        view_layout:
          grid-area: weather
      - type: markdown
        content: Button Area
        view_layout:
          grid-area: buttons
      - type: markdown
        content: Conditional Area
        view_layout:
          grid-area: conditional
```

**Comment by janstadt** [comment]
Awesome much appreciated @j-a-n. Is it possible to move all the stuff from the views into the info box section and make that 100% width and height? Basically what im trying to accomplish is all that stuff in the info box since i want the screen saver functionality to be on all the time. Maybe im over thinking things though and maybe i just keep the screensaver off and use a regular view like the one above and just leverage the full screen functionality of wallpanel.

**Comment by janstadt** [comment]
Here is my current config if thats helpful. Basically looking for an always on fullscreen view for the Lenovo ThinkSmart View.

```
wallpanel:
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: true
  idle_time: 1
  card_interaction: true
  image_fit: cover
  stop_screensaver_on_mouse_move: false
  stop_screensaver_on_mouse_click: false
  stop_screensaver_on_key_down: false
  exclude_media_types:
    - video
  image_url: immich+http://[fqdn]/api
  immich_api_key: [apikey]
  immich_persons:
    - Face 1
    - Face 2
    - Face 3
  cards:
    - type: custom:clock-weather-card
      wp_style:
        width: 80%
        height: 700px
        grid-row: 1
        grid-column: 1
      entity: weather.home
      card_mod:
        style: |
          clock-weather-card-today-right-wrap-top {
            text-align: center !important;
            font-size: 20px;
          }
          clock-weather-card-today-right-wrap-center {
            font-size: 65px;
          }
          clock-weather-card-today-right-wrap-bottom {
            justify-content: center !important;
            font-size: 20px;
          }
      hide_forecast_section: true
      animated_icon: false
    - type: horizontal-stack
      wp_style:
        width: 80%
        height: 10%
        grid-row: 3
        grid-column: 1
      cards:
        - type: custom:mushroom-light-card
          entity: light.jakes_lamp
          fill_container: false
          icon_color: blue
          icon: mdi:lamp
          layout: horizontal
          collapsible_controls: false
        - type: custom:mushroom-light-card
          entity: light.marys_lamp
          fill_container: false
          icon_color: purple
          icon: mdi:lamp
          layout: horizontal
        - type: custom:mushroom-entity-card
          entity: input_boolean.parents_music
          fill_container: false
          tap_action:
            action: toggle
        - type: custom:mushroom-light-card
          entity: light.parents_tablet_backlight
          fill_container: false
          icon_color: amber
          icon: mdi:monitor
          layout: horizontal
          collapsible_controls: false
    - type: conditional
      wp_style:
        grid-column: 2
        width: 90%
        height: 100%
      conditions:
        - condition: state
          entity: input_boolean.parents_music
          state: 'on'
      card:
        type: custom:mediocre-massive-media-player-card
        entity_id: media_player.master_bedroom
        ma_entity_id: media_player.master_bedroom
  style:
    wallpanel-screensaver-info-container:
      padding: 0px
    wallpanel-screensaver-info-box-views:
      width: 100vw
    wallpanel-screensaver-info-box:
      width: 100%
    wallpanel-screensaver-info-box-content:
      width: 100%
      '--wp-card-width': 100%
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-border-width': 0px
      '--card-background-color': black
      '--primary-text-color': '#ffffff'
      '--secondary-text-color': '#dddddd'
      filter: >-
        drop-shadow(0px 0px 3px rgb(17, 17, 17)) drop-shadow(0px 0px 8px rgb(30,
        30, 30))
views:
  - type: sections
    max_columns: 4
    title: home
    path: home
    sections:
      - type: grid
        cards: []
    cards: []

```

**Comment by j-a-n** [comment]
In my example the infobox is containing the view.
```yaml
wallpanel:
  views:
    - title: Home
...
```
Did you have a look at the screensaver?
