### ISSUE TITLE
Weather state based images

### ISSUE THREAD

**Issue by RobertArgo** [j-a-n/lovelace-wallpanel#43]
It would be an amazing addition if the image displayed was related to the weather state. For example, show a picture of the sun if the weather is sunny or a picture of rain if raining. Images could either be local or specific urls. Would this be possible?

**Comment by j-a-n** [comment]
Nice idea!
This should be possible right now.
You can add profiles for the differnet weather conditions with different image URLs, for example:
```
wallpanel:
  profile_entity: input_text.wallpanel_profile
  profiles:
    sunny:
      image_url: https://source.unsplash.com/random/${width}x${height}?sunny&sig=${timestamp}
    rainy:
      image_url: https://source.unsplash.com/random/${width}x${height}?rainy&sig=${timestamp}
```
Then you add an HA automation which changes the value of `input_text.wallpanel_profile` whenever the weather state changes.

**Comment by kamilk91** [comment]
```
wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: true
  idle_time: 60
  screensaver_entity: input_boolean.screensaver_fire
  profile_entity: input_text.wallpanel_profile
  profiles:
    sunny:
      image_url: https://source.unsplash.com/random/${width}x${height}?sunny%20warsaw&sig=${timestamp}
    clear-night:
      image_url: https://source.unsplash.com/random/${width}x${height}?clear-night%20warsaw&sig=${timestamp}
    cloudy:
      image_url: https://source.unsplash.com/random/${width}x${height}?cloudy%20warsaw&sig=${timestamp}
    exceptional:
      image_url: https://source.unsplash.com/random/${width}x${height}?exceptional%20warsaw&sig=${timestamp}
    fog:
      image_url: https://source.unsplash.com/random/${width}x${height}?fog%20warsaw&sig=${timestamp}
    hail:
      image_url: https://source.unsplash.com/random/${width}x${height}?hail%20warsaw&sig=${timestamp}
    lightning:
      image_url: https://source.unsplash.com/random/${width}x${height}?lightning%20warsaw&sig=${timestamp}
    lightning-rainy:
      image_url: https://source.unsplash.com/random/${width}x${height}?lightning-rainy%20warsaw&sig=${timestamp}
    partlycloudy:
      image_url: https://source.unsplash.com/random/${width}x${height}?partlycloudy%20warsaw&sig=${timestamp}
    pouring:
      image_url: https://source.unsplash.com/random/${width}x${height}?pouring%20warsaw&sig=${timestamp}
    rainy:
      image_url: https://source.unsplash.com/random/${width}x${height}?rainy%20warsaw&sig=${timestamp}
    snowy-rainy:
      image_url: https://source.unsplash.com/random/${width}x${height}?snowy-rainy%20warsaw&sig=${timestamp}
    windy:
      image_url: https://source.unsplash.com/random/${width}x${height}?windy%20warsaw&sig=${timestamp}
    windy-variant:
      image_url: https://source.unsplash.com/random/${width}x${height}?windy-variant%20warsaw&sig=${timestamp}



```

here you have sample for all acuweather states
