### ISSUE TITLE
Video Not playing

### ISSUE THREAD

**Issue by maxime-granger** [j-a-n/lovelace-wallpanel#435]
I have a Synology setup.
I have tried for the 1st time to use video file mp4 in my folder but it does not appear to work, the video is not loaded. 

is there a trick to for the video to be displayed ? 
here is my setup 

```yaml
wallpanel:
  enabled: true
  enabled_on_tabs: ''
  debug: false
  hide_toolbar: false
  hide_sidebar: true
  fullscreen: false
  idle_time: 10
  keep_screen_on_time: 86400
  black_screen_after_time: 7200
  control_reactivation_time: 1
  screensaver_stop_navigation_path: /map/test2
  image_url: ${entity:input_select.wallpanel_image_url}
  video_loop: true
  image_fit_landscape: cover
  image_fit_portrait: contain
  image_list_update_interval: 3600
  image_animation_ken_burns: true
  image_animation_ken_burns_zoom: 1.3
  image_animation_ken_burns_delay: 5
  image_background: image
  image_order: random
  image_excludes: []
  show_image_info: false
  fetch_address_data: true
  image_info_template: >-
    ${address.town|address.city!prefix=!suffix= //
    }${DateTimeOriginal!options=year:numeric,month:long}
  touch_zone_size_next_image: 30
  touch_zone_size_previous_image: 30
  screensaver_entity: input_boolean.wallpanel_screensaver
  info_animation_duration_x: 30
  info_animation_duration_y: 30
  info_animation_timing_function_x: ease-in-out
  info_animation_timing_function_y: ease-in-out
  info_move_pattern: random
  info_move_interval: 0
  info_move_fade_duration: 2
  card_interaction: true
  cards:
    - type: weather-forecast
      entity: weather.forecast_maison_2
      show_forecast: true
      forecast_type: hourly
  style:
    wallpanel-screensaver-info-box:
      transform: scale(2, 2)
    wallpanel-screensaver-info-box-content:
      transform: scale(1, 1)
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-border-width': 0px
      text-shadow: >-
        -0.5px -0.5px 0 rgb(17, 17, 17), 0.5px -0.5px 0 rgb(17, 17, 17), -0.5px
        0.5px 0 rgb(17, 17, 17), 0.5px 0.5px 0 rgb(17, 17, 17)
      '--primary-text-color': '#ffffff'
      '--secondary-text-color': '#dddddd'
```
