### ISSUE TITLE
Immich with internal IP

### ISSUE THREAD

**Issue by segdy** [j-a-n/lovelace-wallpanel#439]
I do not expose my immich to external. I do not have SSL, I do not have a reverse proxy.
I am using:

```
wallpanel:
  profiles:
    user.panel:
      enabled: true
      hide_toolbar: false
      hide_sidebar: false
      fullscreen: false
      idle_time: 10
      cards: []
      image_url: immich+http://10.227.4.12:2283/api
      immich_api_key: XXXXXXXX
      immich_shared_albums: true
      views:
        - title: Wallpanel
```

But all I am getting is black. The documentation only talks about CORS, reverse proxy and https. Why is that? Is direct connection as above not supported? If not, why not? I can easily access the API via CURL, I do not see a reason why I would need to go over a reverse proxy ...

Lastly, is the image requested by the HA server or by the client running wall panel? In either case, I confirmed that API access works from both, yet I am still getting just black.

Advice would be appreciated.
