### ISSUE TITLE
wallpanel-screensaver-container height, width and top

### ISSUE THREAD

**Issue by nahumoded** [j-a-n/lovelace-wallpanel#447]
hi
after upgrade yesterday to v4.51.0 the screensaver fit all screen and don't use:
  style:
    wallpanel-screensaver-container:
      width: 100%
      height: 73.5%
      top: 5.0%
is there any fix for this?
thanks

**Comment by j-a-n** [comment]
Could you please test if version 4.52.0 fixes the problem?

**Comment by nahumoded** [comment]
hi
thanks
version 4.52.0 didn't fix it, even after restart ha.
also, when i change for example the width to 50%, i can't exit the screensaver when i touch in the side of the screen, only in the 50% screen from the middle. for a millisecond it looks the real size, and after the images stretch beyond the screen size

**Comment by nahumoded** [comment]
hi
thanks
version 4.52.0 didn't fix it, even after restart ha.
also, when i change for example the width to 50%, i can't exit the
screensaver when i touch in the side of the screen, only in the 50% screen
from the middle. for a millisecond it looks the real size, and after the
images stretch beyond the screen size

בברכה
נחום עודד




‫בתאריך יום ב׳, 16 ביוני 2025 ב-23:47 מאת ‪Jan Schneider‬‏ <‪
***@***.***‬‏>:‬

**Comment by j-a-n** [comment]
I'm unable to reproduce the issue on my end.
Clicking on the left side of the screensaver loads the previous image, while clicking on the right side loads the next image. 
Clicking in the middle stops the screensaver.
This behavior is controlled by the `touch_zone_size_next_image` and `touch_zone_size_previous_image` settings.

Could you let me know what kind of device you're using?
Additionally, please share your wallpanel configuration so I can try to replicate the issue.

**Comment by nahumoded** [comment]
hi
i ment if i wrote in the configuration "width: 50 %", in the first milisecond the screen saver act 50% and after the image stretch beyond the screen size. so when i want to exit from the screensaver, i need to touch in the 50% of the screen only, so its seemed the screensaver act goot, but shown not like the configuration.
i run it om windows 11, and this is my configuration:

```yaml
wallpanel:
  enabled: true
  hide_sidebar: true
  hide_toolbar: false
  fullscreen: false
  idle_time: 12
  image_url: /local/2tbmedia/screensaver/
  display_time: 6
  fade_in_time: 1
  media_order: random
  image_fit: contain
  screensaver_entity: input_boolean.screensaver_some
  cards:
    - type: custom:analog-clock
      hide_SecondHand: false
      locale: he-he
      diameter: 350
      color_HourHand: '#326ba8'
      color_MinuteHand: '#3273a8'
      color_DigitalTime: '#CCCCCC'
      color_FaceDigits: '#a83832'
      color_secondhand: '#a83832'
      color_Ticks: white
      style_hourhand: 5
      style_minutehand: 5
      style_secondhand: 5
      hide_weekday: false
      color_background: false
      card_mod:
        style:
          .: |
            ha-card {        

              background: transparent!important;
              right: 1px!important;
              top: -8px!important;
            }
    - type: weather-forecast
      entity: weather.forecast_home
      show_current: true
      show_forecast: false
      card_mod:
        style:
          .: |
            ha-card {
              transform: scale(1.25);         
              background: transparent;
              right: 800px!important;
              top: -306px!important;
            }
            layout-card$:
               grid-layout$: |
                 :host {
                   padding: 2px !important;
                 }
                 #root {
                   margin: 2px !important;
                 }
                 #root > * {
                   margin: 1px !important;
          ha-card.type-weather-forecast>div.content: |
            svg {
              width: 150px !important;
              height: 100px !important;
              flex: unset !important;
            }
          ha-card.type-weather-forecast>div.forecast: |
            div {
              padding-top: 20px;
              font-size: 50px;
              justify-content: space-evenly !important;
            }
          ha-card.type-weather-forecast>div.content>div.info:
            .: |
              div.name-state {
                display: flex;
                flex-direction: column;
              }
            div.name-state:
              .: |
                div.state {
                  font-size: 40px !important;
                }
                div.name {
                  display: none;
                  max-height: 10px !important;
                }
            div.temp-attribute: |
              .temp {
                font-size: 40px !important;
                padding-bottom: 5px;
              }
              .attribute {
                font-size: 25px !important;
              }  
              .temp span {
                font-size: 15px !important;
                margin-left: -5px;
              }
  style:
    wallpanel-screensaver-container:
      width: 100%
      height: 73.5%
      top: 5.0%
background: center /cover    no-repeat fixed url('/local/kotel5.jpg')
```

**Comment by j-a-n** [comment]
Okay, now I see.
Please add `overflow: hidden`:
```yaml
  style:
    wallpanel-screensaver-container:
      overflow: hidden
      width: 100%
      height: 73.5%
      top: 5.0%
```
