### ISSUE TITLE
Possibility to interact with iframe?

### ISSUE THREAD

**Issue by patienttruth** [j-a-n/lovelace-wallpanel#451]
Greetings,

I may have overlooked a setting, but was wondering if it would be possible to interact with an iframe. It seems Wall Panel casts an invisible "you cannot click" layer, perhaps that's necessary to prevent interacting with the dash in the background. 

Although I understand I can pull images from Immich with Wall Panel, I've got everything configured with Immich Kiosk, and I'd like to be able to interact with it. It has a few features like tagging photos (favorites, and do not display) that I'd like to retain.

Is that a possibility with Wall Panel?

I appreciate that I can overlay cards on Wall Panel, and I'm experimenting with it still. I did notice something about another dash card. 

I'm using https://github.com/bhuebschen/fab-card to make some floating buttons and they show through over Wall Panel, however they don't appear to function. It would be my preference that they could still function, but if they cannot it would be good for them to be hidden behind Wall Panel

Thank you so much!

<details><summary>Wall Panel Config</summary>
<p>

```yaml
wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: true
  fullscreen: false
  idle_time: 30
  keep_screen_on_time: 600
  card_interaction: true
  screensaver_entity: input_boolean.screensaver
  cards:
    - type: weather-forecast
      entity: weather.pirateweather
      show_forecast: true
      forecast_type: daily
  style:
    wallpanel-screensaver-info-box:
      position: 'absolute'
      top: '0.5em'
      right: '0.5em'

      background-color: '#ffffff99'
    wallpanel-screensaver-info-box-content:
      '--ha-card-background': none
      '--ha-card-box-shadow': none
      '--ha-card-border-width': 0px
      '--primary-text-color': '#ffffff'
      '--secondary-text-color': '#dddddd'
  stop_screensaver_on_mouse_move: false
  stop_screensaver_on_mouse_click: false
  iframe_load_unchanged: false
  image_url: >-
    iframe+https://
```

</p>
</details> 

<details><summary>FAB Card Config</summary>
<p>

```yaml
type: custom:fab-card
button_color: black
icon_color: "#FFFFFF"
active_color: "#2257FF"
icon: mdi:monitor-off
action:
  action: call-service
  service: switch.turn_off
  service_data:
    entity_id: switch.salix_screen
offset_y: 80px
animation: bounce
position: bottom-left

``` 
</p>
</details>
