### ISSUE TITLE
Easiest way to move view from left to right side

### ISSUE THREAD

**Issue by segdy** [j-a-n/lovelace-wallpanel#456]
I have this configuration:

```
wallpanel:
  debug: false
  profiles:
    user.panel:
      card_interaction: true
      enabled: true
      hide_toolbar: false
      hide_sidebar: false
      fullscreen: false
      idle_time: 10
      display_time: 5
      cards: []
      image_url: immich+https://xxx
      immich_api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      immich_persons:
        - Person1
        - Person2
        - Person3
      immich_memories: true
      image_order: random
      views:
        - title: Wallpanel
```

Wallpanel view is a hidden view with just a few cards showing basic information (security status etc).

Now the issue is that this view is always shown on the left side and for most of our pictures the interesting part is on the left side (selfies).

What is the easiest way to right-align this thing?

![Image](https://github.com/user-attachments/assets/e2c43e7c-83ed-46dd-83d9-1b7c94433dc1)

I have read about CSS but it's too complicated for me, I was not able to get it working.

**Comment by j-a-n** [comment]
You can try this:
```yaml
wallpanel:
  ...
  style:
    wallpanel-screensaver-info-box-content:
      width: 100vw
    wallpanel-screensaver-info-box-views:
      justify-self: end
      width: 400px
```
