### ISSUE TITLE
Browser-mod integration when clearing cache (and not only then) is showing screensaver in not targeted devices

### ISSUE THREAD

**Issue by kamilk91** [j-a-n/lovelace-wallpanel#47]
There are 3 devices, call it:
`Desktop` - not included in brwosermod filter
`Oneplus` - not included in brwosermod filter
`firebrowser` - **included** in browsermod filter

My configuration is:

```
wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: true
  idle_time: 60
  display_time: 60
  screensaver_entity: input_boolean.screensaver_firebrowser
  profile: sunny
  profile_entity: input_text.wallpanel_profile
  cards:
  #.......
```

My target is to show screensaver only on `firebrowser` device, and it is only one registered in browser mod. 
Current behavior of screensaver with `Desktop` is that when i use `shift + R` to make hard refresh it starts to force Fullscreen mode in my browser, and starting screensaver after `idle_time`. It won't be problem, because it is not often situation that im clearing full cache, but its kind of worst with my `Oneplus`.
It looks like its "hard-refreshed" everytime app starts. The result is that all `Wallpanel` actions are running everytime i open my application in `Oneplus`.

I have also tried to check if it isn't a `browser-mod` bug, so i opened app on all devices with cache cleared, and then ran "Popup" targeted to `firebrowser`. It has opened only in `firebrowser` device so it works good.

So, this behavior is very hard, because i can't normally use my app my mobile devices, like my fiance on iOS can't do it also. 

Do you know any possibilities to fix this problem, or maybe some advices what i can try? 
Thank you 
Kamil.

**Comment by kamilk91** [comment]
I mad a little "hack" with my friend help (im not familiar with frontend) in updateConfig()

```
function updateConfig() {
	const params = new URLSearchParams(window.location.search);
	const user = elHass.__hass.user.name ? elHass.__hass.user.name.toLowerCase().replace(/\s/g, '_') : null;
	
	config = {};
	
	
	mergeConfig(config, defaultConfig);

	mergeConfig(config, getHaPanelLovelaceConfig());

	console.log(window.browser_mod.browserId);
// force fire browser
	if(window.browser_mod.browserID === "fire"){
	    
	config.enabled = true;
	}
	

```

**Comment by j-a-n** [comment]
You can disable wallpanel by default, and enable for the device firebrowser only:
```yaml
wallpanel:
  enabled: false
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: true
  idle_time: 60
  display_time: 60
  screensaver_entity: input_boolean.screensaver_firebrowser
  profile: device_${browser_id}
  profile_entity: input_text.wallpanel_profile
  profiles:
    device_firebrowser:
      enabled: true
  cards:
  #.......
```
