### ISSUE TITLE
url in android companion app

### ISSUE THREAD

**Issue by pacmac** [j-a-n/lovelace-wallpanel#49]
I have the companion app installed on a new nsPanelPro, and I am unable to set the url to anything other than the hostname & port and are therefore unable to activate wallpanel on that device only:

```http://hass:8123/lovelace/default_view?wp_enabled=true```

If I set that in the companion app, the path gets removed back to:

```http://hass:8123/```

is there a solution ??

**Comment by j-a-n** [comment]
You can use browser mod to enable wallpanel on selected devices. Please see the README and #47.

**Comment by pacmac** [comment]
Thanks, but I really dont want to install browser mod just to do that :-)

**Comment by pacmac** [comment]
Also, I have enabled wallpanel for specific tab (nspp_home) and have hidden all other tabs except for that one for a specific user (nspp):

```
wallpanel:
  enabled_on_tabs:
    - nspp_home
  enabled: true
  hide_toolbar: true
  hide_sidebar: true
  fullscreen: false
```

when I view the refreshed / reloaded / restarted screen on the android / nspanel device, all of the tabs in the toolbar are hidden correctly, and only the one tab 'nspp_home' is visible but the sidebar is still accessible.
