### ISSUE TITLE
Possibility to animate individual cards

### ISSUE THREAD

**Issue by Bort89** [j-a-n/lovelace-wallpanel#52]
First things first: this module is awesome! I am recreating my Dakboard and making great progress! :)

I have a HA dashboard on a 24 inch screen in the center of my livingroom but most of the time it shows this excellent wallpanel with pictures from Google photos. It also shows a calendar, time, weather, etc. etc.

You can imagine that I want the calendar to stay in place while other cards may animate their position.
Is this possible? I tried with css to the wp_style and with your options to the same wp_style but didn't get it to work.

TLDR; Is it possible to animate individual cards?

Keep up the good work!

**Comment by j-a-n** [comment]
With version 4.4 I added the ability to set the parent element of each card by element id.
For example:
```yaml
  cards:
    - type: markdown
      content: Fixed position
      wp_style:
        parent: wallpanel-screensaver-container
        position: fixed
        top: 10px
        left: 10px
        width: 300px
        height: 200px
```
You can play around with it and give me feedback.
