### ISSUE TITLE
Add service to enable/disable wallpanel from an automation

### ISSUE THREAD

**Issue by cben0ist** [j-a-n/lovelace-wallpanel#56]
Hi,
I use an automation to display the front porch camera feed on my tablets whenever motion have been detected on that area.
Tablets have fully browser and I am using browser_mod.popup to display the camera feed.
Wallpanel is awesome but I did not find a way to "wake up" these screens so the popup is displayed behind wallpanel so we cannot see it.
Would there be a service to disable/enable wallpanel that I can use in my automation? Or is there already a way to do that same thing?
Thank you!

**Comment by Bort89** [comment]
Check the docs: :) <html>
<body>


screensaver_entity | An entity of type 'input_boolean' to reflect and change the screensaver state (on = started, off = stopped). If browser_mod is installed, ${browser_id} will be replaced with Browser ID (see below).
-- | --



</body>
</html>

I just created a helper input boolean.

**Comment by j-a-n** [comment]
You can use [profiles](https://github.com/j-a-n/lovelace-wallpanel#profiles) for that.
Create an input_select or input_text helper in HA and then set `profile_entity` accordingly. After that you can switch profiles via automation.
e.g.:
```yaml
wallpanel:
  profiles:
    screensaver_on:
      idle_time: 10
    screensaver_off:
      idle_time: 0
  profile_entity: input_text.wallpanel_profile
```

**Comment by cben0ist** [comment]
Ohhhh, I am going to give it a try then and will share my results here!
Thank you!

**Comment by cben0ist** [comment]
I have not tested the screensaver_entity option yet but the profile solution works like a charm!
I just had to include enabled true/false to the profile or the panel would not wake up on "screensaver_off". It does with _enabled: false_ in the corresponding profile!

Thank you!

```
  profiles:
    screensaver_on:
      enabled: true
      idle_time: 1
    screensaver_off:
      enabled: false
      idle_time: 0
  profile_entity: input_text.wallpanel_profile
```
