### ISSUE TITLE
Option to dim the screen

### ISSUE THREAD

**Issue by LukaszP2** [j-a-n/lovelace-wallpanel#6]
It is screen sever so can you add option to dim the screen?

**Comment by j-a-n** [comment]
Do you mean reducing the brightness of the backlight or darkening the colors?

**Comment by LukaszP2** [comment]
Both options will be great

**Comment by j-a-n** [comment]
There is no web API for dimming the backlight.
With version 2.2 of the addon, there is an overlay div that allows you to dim the entire screen.
For example:
```yaml
  style:
    wallpanel-screensaver-overlay:
      background: '#000000aa'
```
