### ISSUE TITLE
grid-row span possible

### ISSUE THREAD

**Issue by Vinisz** [j-a-n/lovelace-wallpanel#69]
Hi,
        
        I have everything working just fine now on an android tablet with the companion app. 
        I'm already 90% happy with the dashboard, but just one question which would help.
        Is it possible to "span" on rows as well instead of columns ? 
        I would like to do something like this :
        
        _grid-row: 1 / span 3_

**Comment by j-a-n** [comment]
Yes you can.
Try this example:
```yaml
  cards:
    - type: markdown
      content: Card 1
      wp_style:
        width: 810px
        grid-row: 1
        grid-column: 1 / span 2
    - type: markdown
      content: Card 2
      wp_style:
        width: 400px
        grid-row: 2
        grid-column: 2
    - type: markdown
      content: Card 3
      wp_style:
        width: 400px
        grid-row: 2 / span 2
        grid-column: 1
    - type: markdown
      content: Card 4
      wp_style:
        width: 400px
        grid-row: 3
        grid-column: 2
```
