### ISSUE TITLE
Entity not available weather.home

### ISSUE THREAD

**Issue by Rayeliint** [j-a-n/lovelace-wallpanel#83]
Hi there, getting my head around this slowly but cant work out when the screen saver is activated I get the message "Entity not available weather.home"
What do I need to change and where please?
Other than that loving your work!!

**Comment by j-a-n** [comment]
Hi!
Please have a look at [Badges and cards](https://github.com/j-a-n/lovelace-wallpanel#badges-and-cards)
By default one card is configured to show in the info box on top of the photos.
```yaml
cards:
  - type: weather-forecast
    entity: weather.home
    show_forecast: true
```
You can change that in the configuration to display other cards if you like.
You can also use the following dashboard config to not show any card:
```yaml
wallpanel:
  ...
  cards: []
```
