### ISSUE TITLE
four boxs

### ISSUE THREAD

**Issue by LukaszP2** [j-a-n/lovelace-wallpanel#89]
I want to do something like that... How can I do that?
<img width="958" alt="Bez tytułu" src="https://user-images.githubusercontent.com/44735995/229109507-c38822e1-9b7a-4932-8d16-3d7ac45bea71.png">

**Comment by j-a-n** [comment]
You can try this as a basis:

```
  style:
    wallpanel-screensaver-info-box-content:
      width: 'calc(100vw - 50px)'
      height: 'calc(100vh - 50px)'
      justify-content: 'space-between'
      align-content: 'space-between'
  cards:
    - type: markdown
      content: Card 1
      wp_style:
        width: 400px
        grid-row: 1
        grid-column: 1
    - type: markdown
      content: Card 2
      wp_style:
        width: 400px
        grid-row: 1
        grid-column: 2
    - type: markdown
      content: Card 3
      wp_style:
        width: 400px
        grid-row: 3
        grid-column: 1
    - type: markdown
      content: Card 4
      wp_style:
        width: 400px
        grid-row: 3
        grid-column: 2
```

**Comment by LukaszP2** [comment]
how add this code to box?
```
    - type: custom:digital-clock
      dateFormat:
        weekday: long
        day: numeric
        month: long
        year: numeric
      timeFormat:
        hour: 2-digit
        minute: 2-digit
```

**Comment by j-a-n** [comment]
```yaml
  style:
    wallpanel-screensaver-info-box-content:
      width: 'calc(100vw - 50px)'
      height: 'calc(100vh - 50px)'
      justify-content: 'space-between'
      align-content: 'space-between'
  cards:
    - type: custom:digital-clock
      dateFormat:
        weekday: long
        day: numeric
        month: long
        year: numeric
      timeFormat:
        hour: 2-digit
        minute: 2-digit
      wp_style:
        width: 400px
        grid-row: 1
        grid-column: 1
    - type: markdown
      content: Card 2
      wp_style:
        width: 400px
        grid-row: 1
        grid-column: 2
    - type: markdown
      content: Card 3
      wp_style:
        width: 400px
        grid-row: 3
        grid-column: 1
    - type: markdown
      content: Card 4
      wp_style:
        width: 400px
        grid-row: 3
        grid-column: 2
```
