### ISSUE TITLE
How to blur the background of card?

### ISSUE THREAD

**Issue by taikun114** [j-a-n/lovelace-wallpanel#9]
I tried using "backdrop-filter: blur(16px)" to blur the background of a semi-transparent card, but it doesn't work.
How can I get this to work?

**Comment by j-a-n** [comment]
You can try to add the `backdrop-filter` to `wallpanel-screensaver-info-box`
```yaml
wallpanel:
  style:
    wallpanel-screensaver-info-box:
      backdrop-filter: blur(16px)
```

**Comment by taikun114** [comment]
Thank you.

I tried it but it did not work.
The top of the card was just a little blurry, not the back of the card.

I tried "opacity" and "rgba" to make the card translucent, but it didn't change
![スクリーンショット 2022-08-15 20 49 05](https://user-images.githubusercontent.com/98800458/184630691-fbe8830f-6bd5-4499-a466-ebb680c8a37a.png)
.

**Comment by taikun114** [comment]
Sorry, I adjusted the settings again and noticed that the back of the card is now blurred, but not where it overlaps the card, but the area including a little outside of the card is blurred. How can I blur only the area that just overlaps the card?
![スクリーンショット 2022-08-15 21 01 57](https://user-images.githubusercontent.com/98800458/184631851-fdc553e6-66de-4bea-8e10-78950116736e.png)

**Comment by j-a-n** [comment]
You could add `backdrop-filter` to the card style (`wp_style` atribute):
```
cards:
    - type: markdown
      content: Example
      wp_style:
        backdrop-filter: blur(16px);
```

**Comment by taikun114** [comment]
Thank you.

I thought I got it right this time, but when I look closer, I see that the image is blurred to a little outside of the card.
![スクリーンショット 2022-08-15 21 31 39](https://user-images.githubusercontent.com/98800458/184635724-f9a63847-598e-41b7-af06-fc3fbc14edfd.png)

**Comment by taikun114** [comment]
I just couldn't get it to blur just the overlapping area of the card, so I decided to use the following setup.

```
  style:
    wallpanel-screensaver-info-box:
      '--ha-card-background': rgba(0, 0, 0, 0.5)
      box-shadow: 0px 0px 16px 0px rgba(0, 0, 0, 0.5)
      '--ha-card-box-shadow': 0px 0px 8px 0px rgba(0, 0, 0, 0.25)
      background: rgba(30, 30, 30, 0.5)
      padding: 8px
      backdrop-filter: blur(16px)
      border-radius: 24px
    wallpanel-screensaver-info-box-content:
      '--primary-text-color': '#e1e1e1'
      '--secondary-text-color': '#9b9b9b'
```
![スクリーンショット 2022-08-15 23 31 29](https://user-images.githubusercontent.com/98800458/184656716-7ca753b7-ed83-4b21-be2c-f9a2f07ceef3.png)


Please let me know if there is a way to blur just the overlapping area of the card.

Thank you very much for all your help.

**Comment by j-a-n** [comment]
You can use margin instead of padding for the cards:
```
style:
  wallpanel-screensaver-info-box:
    '--wp-card-padding': 0px
cards:
  - type: markdown
    content: Example
    wp_style:
      backdrop-filter: blur(16px)
      margin: 5px
```

**Comment by taikun114** [comment]
I used "padding" to expand the background on the back of the cards, is there any problem with this?

**Comment by j-a-n** [comment]
If your cards have a padding, the padding will be also blurred.

**Comment by taikun114** [comment]
I don't use padding on my cards, so I think I can keep it that way.  

One question (not sure if this is the right place to ask this), there is a little margin above the top most card, how can this be removed? I don't use "padding-top" but there is a little more margin only on the top than on the left and right.

**Comment by j-a-n** [comment]
With version 2.2 of the addon something like the following is sufficient:

```yaml
  style:
    wallpanel-screensaver-info-box:
      '--wp-card-backdrop-filter': blur(16px)
      '--ha-card-background': '#00000066'
```
