### ISSUE TITLE
Hide toolbar broken in latest HA beta 2023.04bx

### ISSUE THREAD

**Issue by TheZoker** [j-a-n/lovelace-wallpanel#91]
Hi there,

Currently the "hide toolbar" option is broken within my instance. I'm not sure if this is caused by me running the latest beta, which apparently broke many custom frontend projects like `button-card` or just an issue with my instance. 
I can't tell for sure, since I just started using this project and don't know if the toolbar hide option worked in the none beta version before. 

Here is my config code for the dashboard:
```yaml
wallpanel:
  enabled: true
  hide_toolbar: true
  fullscreen: true
  idle_time: 0
```

This is the HTML structure in the latest beta:
![image](https://user-images.githubusercontent.com/1368405/229634395-e58c47f9-67f6-49e1-96cb-416886acc659.png)

Please let me know, if there is anything I can test!

Thanks!
