### ISSUE TITLE
keep_screen_on_time no longer works after upgrade to 2023.04

### ISSUE THREAD

**Issue by TheDuke427** [j-a-n/lovelace-wallpanel#93]
No issues with the code before the OS upgrade, but now this feature no longer works and device screens turn off at the system defined display variable. Here my YAML:

```

wallpanel:
  enabled: true
  hide_toolbar: false
  hide_sidebar: false
  fullscreen: true
  idle_time: 60
  keep_screen_on_time: 86400
  black_screen_after_time: 0
  control_reactivation_time: 1
  screensaver_stop_navigation_path: /wall-panel/0
  image_url: http://picsum.photos/${width}/${height}?random=${timestamp}
  image_fit: cover
  image_list_update_interval: 3600
  image_order: sorted
  image_excludes: []
  show_image_info: false
  fetch_address_data: true
  image_info_template: >-
    ${address.town|address.city!prefix=!suffix= //
    }${DateTimeOriginal!options=year:numeric,month:long}
  screensaver_entity: input_boolean.wallpanel_screensaver
  info_animation_duration_x: 30
  info_animation_duration_y: 11
  info_animation_timing_function_x: ease-in-out
  info_animation_timing_function_y: ease-in-out
  info_move_pattern: random
  info_move_interval: 0
  info_move_fade_duration: 2
  style:
    wallpanel-screensaver-info-box:
      font-size: 3vh
      font-weight: 400
      color: '#eeeeee'
      opacity: 0.5
  cards:
    - type: custom:clock-weather-card
      entity: weather.forecast_home
      show_forecast: true
```
